### ISSUE TITLE
Create structs for machine readable output

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1062]
related to https://github.com/redhat-developer/odo/issues/784

Define how the output will look like before starting with implementation.

The first stage should be showing it on json/yaml examples, and then defining go structs that are going to represent the output.

**Comment by surajnarwade** [comment]
as per #1110, 

* odo describe
```
$ odo describe nodejs-ex-nodejs-msbk -o json | jq
{
  "componentName": "nodejs-ex-nodejs-msbk",
  "type": "nodejs",
  "source": "file:///home/snarwade/odo-example/nodejs-ex",
  "url": [
    {
      "name": "nodejs-ex-nodejs-msbk",
      "url": "nodejs-ex-nodejs-msbk-nodejs-ex-xjsy-myproject.192.168.42.73.nip.io",
      "protocol": "http",
      "port": 8080
    }
  ],
  "storage": [
    {
      "name": "data1",
      "size": "100M",
      "path": "/data"
    }
  ]
}
```

* odo app describe

```
$ odo app describe nodejs-ex-xjsy -o json | jq
{
  "applicationName": "nodejs-ex-xjsy",
  "components": [
    {
      "componentName": "nodejs-ex-nodejs-msbk",
      "type": "nodejs",
      "source": "file:///home/snarwade/odo-example/nodejs-ex",
      "url": [
        {
          "name": "nodejs-ex-nodejs-msbk",
          "url": "nodejs-ex-nodejs-msbk-nodejs-ex-xjsy-myproject.192.168.42.73.nip.io",
          "protocol": "http",
          "port": 8080
        }
      ],
      "storage": [
        {
          "name": "data1",
          "size": "100M",
          "path": "/data"
        }
      ]
    }
  ]
}
```

* odo url list

```
$ odo url list -o json | jq
[
  {
    "name": "nodejs-ex-nodejs-msbk",
    "url": "nodejs-ex-nodejs-msbk-nodejs-ex-xjsy-myproject.192.168.42.73.nip.io",
    "protocol": "http",
    "port": 8080
  }
]
```

Looks good ? @kadel  @dgolovin @mohitsuman @cdrage ?

**Comment by kadel** [comment]
as discussed here https://github.com/redhat-developer/odo/issues/784#issuecomment-438627275 can we use Kubernetes object basic strucutre?
Fields like Kind and structs versioning would be great to make this future proof

**Comment by surajnarwade** [comment]
Future Proof output structure:

* `odo describe`

```
kind: Component
apiVersion: odo.openshift.io/v1alpha1
metadata:
  name: nodejs-ex-nodejs-bqtz
  creationTimestamp: 
spec:
  componentName: nodejs-ex-nodejs-bqtz
  type: nodejs
  source: file:///home/snarwade/odo-example/nodejs-ex
  url:
  - name: nodejs-ex-nodejs-bqtz-8080
    url: nodejs-ex-nodejs-bqtz-8080-nodejs-ex-cpct-myproject.192.168.42.73.nip.io
    protocol: http
    port: 8080
  environment:
  - name: abc
    value: xyz
  storage:
  - name: data1
    size: 100M
    path: "/data"
```

* `odo app describe`

```
kind: Application
apiVersion: odo.openshift.io/v1alpha1
metadata:
  name: nodejs-ex-cpct
  creationTimestamp: 
spec:
  components:
  - componentName: nodejs-ex-nodejs-bqtz
    type: nodejs
    source: file:///home/snarwade/odo-example/nodejs-ex
    url:
    - name: nodejs-ex-nodejs-bqtz-8080
      url: nodejs-ex-nodejs-bqtz-8080-nodejs-ex-cpct-myproject.192.168.42.73.nip.io
      protocol: http
      port: 8080
    environment:
    - name: abc
      value: xyz
    storage:
    - name: data1
      size: 100M
      path: "/data"
  - componentName: nodejs-ex-nodejs-pswv
    type: nodejs
    source: file:///home/snarwade/odo-example/nodejs-ex
```

* `odo list`

```
apiVersion: odo.openshift.io/v1alpha1
items:
- apiVersion: odo.openshift.io/v1alpha1
  kind: Component
  metadata:
    creationTimestamp: null
  spec:
    componentName: nodejs-ex-nodejs-bqtz
    environment:
    - name: abc
      value: xyz
    source: file:///home/snarwade/odo-example/nodejs-ex
    storage:
    - name: data1
      path: /data
      size: 100M
    type: nodejs
    url:
    - name: nodejs-ex-nodejs-bqtz-8080
      port: 8080
      protocol: http
      url: nodejs-ex-nodejs-bqtz-8080-nodejs-ex-cpct-myproject.192.168.42.73.nip.io
- apiVersion: odo.openshift.io/v1alpha1
  kind: Component
  metadata:
    creationTimestamp: null
  spec:
    componentName: nodejs-ex-nodejs-pswv
    source: file:///home/snarwade/odo-example/nodejs-ex
    type: nodejs
kind: List
metadata: {}
```

@kadel , @jorgemoralespou , @cdrage @cmoulliard , does this look good :question: 
I am still working on it though

**Comment by cdrage** [comment]
That looks great. Although it does look VERY similar to a Kubernetes operator! 

We should follow by example similar to this process: https://itnext.io/building-an-operator-for-kubernetes-with-the-sample-controller-b4204be9ad56

With regards to your "list" example @surajnarwade it looks like metadata is blank, is that intentional?

**Comment by surajnarwade** [comment]
@cdrage , as per https://github.com/redhat-developer/odo/issues/784#issuecomment-438627275 we want this output to look like CRDs so that we when we implement operator in future, it will help us

For list, I followed `kubectl get pods -o json` and it was empty too

**Comment by jorgemoralespou** [comment]
@surajnarwade if you followed pod, then in the metadata you will find at least name and a list of labels, which we do have.
componentName should be replaced by metadata.name

**Comment by jorgemoralespou** [comment]
@surajnarwade didn't noticed Charlie was only referring to List. In any case:
- there's missing labels everywhere, and these are critical
- componentName should probably changed to name, as component is already implied by the type, and should be moved to the metadata, so: s/spec.componentName/metadata.name

**Comment by cdrage** [comment]
I believe that each output *must* or should always have information under metadata pertaining to Odo. I think we should follow examples from: https://itnext.io/building-an-operator-for-kubernetes-with-the-sample-controller-b4204be9ad56

**Comment by kadel** [comment]
application structure shouldn't contain a whole component definition, it should just reference a component name or some other unique identification that can be used to obtain whole component definition

**Comment by surajnarwade** [comment]
@kadel , \since `kubectl get pods -o json` gives list with whole pod defination that's why I added
But I will make it just a list

**Comment by surajnarwade** [comment]
*
```
$ odo list -o json
apiVersion: odo.openshift.io/v1alpha1
items:
- Active: true
  Name: nodejs-ex-nodejs-opdn
  Type: nodejs
kind: List
metadata: {}
```

*
```
$ odo app list -o json
apiVersion: odo.openshift.io/v1alpha1
items:
- active: true
  activeComponent: nodejs-ex-nodejs-opdn
  name: nodejs-ex-akqh
  project: myproject
kind: List
metadata: {}
```

*
```
 $ odo describe nodejs-ex-nodejs-opdn -o json
apiVersion: odo.openshift.io/v1alpha1
kind: Component
metadata:
  creationTimestamp: null
  name: nodejs-ex-nodejs-opdn
spec:
  environment:
  - name: a
    value: b
  - name: b
    value: c
  source: file:///home/snarwade/odo-example/nodejs-ex
  storage:
  - name: data1
    path: /data
    size: 100M
  type: nodejs
  url:
  - name: nodejs-ex-nodejs-opdn-8080
    url: nodejs-ex-nodejs-opdn-8080-nodejs-ex-akqh-myproject.192.168.42.51.nip.io
```

*
```
$ odo app describe -o json
apiVersion: odo.openshift.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: nodejs-ex-akqh
spec:
  components:
  - environment:
    - name: a
      value: b
    - name: b
      value: c
    name: nodejs-ex-nodejs-opdn
    source: file:///home/snarwade/odo-example/nodejs-ex
    storage:
    - name: data1
      path: /data
      size: 100M
    type: nodejs
    url:
    - name: nodejs-ex-nodejs-opdn-8080
      url: nodejs-ex-nodejs-opdn-8080-nodejs-ex-akqh-myproject.192.168.42.51.nip.io
```

@kadel  I tried to reduce the output as per your suggestions

**Comment by kadel** [comment]
If we want to follow Kubernetes struct `List` needs to contain the whole objects see this as an example https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/list.yaml


```
$ odo list -o json
apiVersion: odo.openshift.io/v1alpha1
kind: List
items:
 - apiVersion: odo.openshift.io/v1alpha1
    kind: Application
    metadata:
      name: nodejs-ex-akqh
    spec:
     components:
        .....
```

**Comment by kadel** [comment]
You are still including the whole component description in the application. 

In the Application object you should just point to the component, not have the whole definitino of the component there.
```
apiVersion: odo.openshift.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  components:
     - name: my-component
     - name: my-second-component
```


Component holds most of the info:
```
apiVersion: odo.openshift.io/v1alpha1
kind: Component
metadata:
  name: nodejs-ex-nodejs-opdn
spec:
  source: file:///home/snarwade/odo-example/nodejs-ex
  type: nodejs
  environment:
  - name: a
    value: b
  - name: b
    value: c
  storage:
  - name: data1
  url:
    - name: nodejs-ex-nodejs-opdn-8080
```
Notice that storage just points to storage name nothing more, the same for url.
We should consider if maybe Components shouldn't contain also `application` field


```
apiVersion: odo.openshift.io/v1alpha1
kind: Url
metadata:
  name: nodejs-ex-nodejs-opdn-8080
spec:
  url: url: nodejs-ex-nodejs-opdn-8080-nodejs-ex-akqh-myproject.192.168.42.51.nip.io
  targetPort: 8080
```


```
apiVersion: odo.openshift.io/v1alpha1
kind: Storage
metadata:
  name: data1
spec:
     path: /data
     size: 100M
```
