### ISSUE TITLE
odo should only create containers being used by devfile commands

### ISSUE THREAD

**Issue by maysunfaisal** [redhat-developer/odo#4318]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

## How did you run odo exactly?
odo push with two components in a devfile, where only one component is being used by the command. For example, consider this devfile:
```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
  attributes:
    alpha.build-context: src
    alpha.build-dockerfile: Dockerfile
components:
  - name: buildguidance
    attributes:
      tool: console-import
    container:
      image: buildguidanceimage-placeholder
      memoryLimit: 1024Mi
      endpoints:
        - name: http-3001
          targetPort: 3001
  - name: runtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - id: install
    exec:
      component: runtime
      commandLine: npm install
      workingDir: /project/src
      group:
        kind: build
        isDefault: true
  - id: run
    exec:
      component: runtime
      commandLine: npm start
      workingDir: /project/src
      group:
        kind: run
        isDefault: true
```

`runtime` is the only component used by the command, whereas `buildguidance` is not. However, odo creates a redundant container for `buildguidance` which is not used by the command

## Actual behavior
odo creates a redundant container for `buildguidance` which is not used by the command

## Expected behavior
this odo component should only have one container in its pod ie - `runtime`

## Any logs, error output, etc?
N/A

P.S. - I think this was agreed upon when first working with devfile v2 but it may have slipped through the cracks.
