### ISSUE TITLE
port names should match endpoint names

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#4737]
Assuming that devfile containers have following endpoints
```
      endpoints:
        - name: first
          targetPort: 3000
        - name: second
          targetPort: 4000
```

The k8s Service that gets generated for odo should have matching port names

Current situation:
```
  ports:
  - name: port-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-4000
    port: 4000
    protocol: TCP
    targetPort: 4000
```

/priority high
/kind bug

**Comment by mik-dass** [comment]
The service port naming is done here https://github.com/devfile/library/blob/5d88bd3c1220097161ef07d78c9fe7605be24ab7/pkg/devfile/generator/utils.go#L229.

**Comment by kadel** [comment]
> The service port naming is done here https://github.com/devfile/library/blob/5d88bd3c1220097161ef07d78c9fe7605be24ab7/pkg/devfile/generator/utils.go#L229.

We should coordinate with the Devfiles team to change this.

**Comment by mik-dass** [comment]
Currently we allow multiple URLs on the same port, but k8s doesn't allow services to have two ports with the same port number and protocol combination.

**Comment by kadel** [comment]
This problem was again raised by user on slack

> I'm using odo 2.3.1 with OpenShift 4.9 and trying to set the Service port name in the devfile, but it wont stick. I always get a default value of name: "port-8080" in my Service when what I want is a port name of "http" (for Service  Mesh and Kiali usage). Here is my devfile snippet, any ideas what I need to set:
> components:
> - container:
>     endpoints:
>     - exposure: public
>       name: "http"
>       path: /
>       targetPort: 8080

**Comment by valaparthvi** [comment]
>The service port naming is done here https://github.com/devfile/library/blob/5d88bd3c1220097161ef07d78c9fe7605be24ab7/pkg/devfile/generator/utils.go#L229.

These changes were made to accommodate another issue that odo was facing, see #4060, https://github.com/devfile/api/issues/287, and https://github.com/devfile/library/pull/51.

**Comment by yangcao77** [comment]
> Currently we allow multiple URLs on the same port, but k8s doesn't allow services to have two ports with the same port number and protocol combination.

This is also because another issue that tools will face. As devfile allows multiple endpoints within same component to use same port. but you can only expose a port number once in a K8s service. In other word, if it behavior as described in the main issue description, the K8s service spec generated will be invalid :

```
      endpoints:
        - name: first
          targetPort: 3000
        - name: second
          targetPort: 3000
```

The k8s Service that gets generated is valid:

```
  ports:
  - name: first
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: second
    port: 3000
    protocol: TCP
    targetPort: 3000
```
