### ISSUE TITLE
Automate release pipeline for odo

### ISSUE THREAD

**Issue by mohammedzee1000** [redhat-developer/odo#4854]
We have pieces in place for doing releases for odo, but not in a way that can be easily automated.

I am considering having one single script that consumes a yaml and helps do release in a simplified way through cii.

The first step is to have a script that does what we can currently do via scripts + move the errata to QE
example yaml file:
```yaml
# Warning: All components in each file are assumed to release in single advisory. If you need separate
# advisories, please have separate config files"
errata:
  type: "RHEA"
  product:
    full_name: "Openshift Developer Tools and Services"
    short_name: "OCP-Tools"
    full_release_prefix: "OCP Tools "
    full_release_suffix: "4.7.z"
    short_release_prefix: "OCP-Tools-"
    short_release_suffix: "4.7-RHEL-8"
  owners: # owners should only include kerberos_id or first half of email in case of manager group
    package: "moahmed"
    qa: "pkumari"
    docs: "pchandra"
    manager: "shp-list"
  tps:
    arch:
      - "x86_64"
      - "s390x"
      - "ppc64le"
    profile:
      prefix: "stable-ocp-tools-"
      suffix: "4.7-for-rhel-8"
  keywords:
    - "odo"
    - "developer"
  topic: "Updated odo binary is now available"
  synopsys: "Openshift Developer Tools and Services odo CLI binaries X.X.X release"
  description: >-
    Openshift Developer Tools and Services odo is a simple CLI tool for developers to create,
    build, and deploy applications on Kubernetes and OpenShift. The odo tool is completely
    client-based and requires no server within the Kubernetes or OpenShift cluster for
    deployment. It detects changes to local code and deploys it to the cluster
    automatically, giving instant feedback to validate changes in real-time. It
    supports multiple programming languages and frameworks.
  description_issues:
    - "Release of odo X.X.X"
  solution: "Download and install a new CLI binary by following the instructions linked from the References section."
  references: "https://docs.openshift.com/container-platform/4.7/cli_reference/developer_cli_odo/installing-odo.html"
  bugzilla_bug_ids:
    - 1
components:
  rpms:
    - name: "odo-cli"
      nvr:
        name: "odo"
        version: "2.2.0"
        release: "1"
        suffix: ".el8"
      build:
        git_repo: "https://github.com/openshift/odo"
        git_target: "main"
        dist_git_repo: "pkgs.devel.redhat.com/rpms/odo" # this is url w/o protocol or owner. ssh will be used automatically with package owner
        dist_git_branch_prefix: "ocp-tools-"
        dist_git_branch_suffix: "4.7-rhel-8"
        sources_tarball_glob: "dist/rpmbuild/SOURCES/openshift-odo-*.tar.gz" # glob of path relative to git repo
        pre_sync_script: "scripts/rpm-prepare.sh" # script to run after cloning git epo, in the git repo
        sync_git_dist_git: # file globs to sync from git to dist-git. Noe empty, all files will be synced
          - glob: "dist/rpmbuild/SPECS/openshift-odo.spec"
            maintain_path: False
        # post_sync_script: "" A script to run in dist gi after file sync
        commit_message: "Building new odo version"
        srpm_glob: "odo*.src.rpm"

```
