### ISSUE TITLE
missing parameters in `odo catalog describe service` output

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#4916]
/kind bug
/area service
/area service-operators

## What versions of software are you using?

using minikube

**Output of `odo version`:**
```
▶ odo version
odo v2.2.3 (9237d8d21)
```

## How did you run odo exactly?
installed olm and Crunchy PostgreSQL (https://operatorhub.io/operator/postgresql)

```
apiVersion: v1
kind: Namespace
metadata:
  name: my-postgresql
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-postgresql
spec:
  targetNamespaces:
  - petclinic
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-postgresql
  namespace: my-postgresql
spec:
  channel: stable
  name: postgresql
  source: operatorhubio-catalog
  sourceNamespace: olm
```

```
▶ odo catalog describe service postgresoperator.v4.7.0/Pgcluster
```

## Actual behavior
```
Kind: Pgcluster
Version: v1
Description: Represents a Postgres primary cluster member
Parameters:

 PATH                         DISPLAYNAME                     DESCRIPTION                    

 ccpimage                     PostgreSQL Image                The Crunchy PostgreSQL image   
                                                              to use. Possible values are    
                                                              "crunchy-postgres-ha" and      
                                                              "crunchy-postgres-gis-ha"      
 ccpimagetag                  PostgreSQL Image Tag            The tag of the PostgreSQL      
                                                              image to use. Example is       
                                                              "centos8-13.3-4.7.0"           
 clustername                  PostgreSQL Cluster name         The name that is assigned      
                                                              to this specific PostgreSQL    
                                                              cluster                        
 database                     Initial PostgreSQL database     The name of the initial        
                              name                            database to be created inside  
                                                              of the PostgreSQL cluster,     
                                                              e.g. "hippo"                   
 exporterport                 PostgreSQL Monitor Port         The port to use for the        
                                                              PostgreSQL metrics exporter    
                                                              used for cluster monitoring,   
                                                              e.g. "9187"                    
 name                         PostgreSQL CRD name             The name of the CRD entry.     
                                                              Should match the PostgreSQL    
                                                              Cluster name                   
 pgbadgerport                 pgBadger Port                   The port to use for the        
                                                              pgBadger PostgreSQL query      
                                                              analysis service, e.g. "10000" 
 port                         PostgreSQL Port                 The port to use for the        
                                                              PostgreSQL cluster, e.g.       
                                                              "5432"                         
 PrimaryStorage               PostgreSQL Primary Storage      Attributes that help set       
                                                              the primary storage of a       
                                                              PostgreSQL cluster             
 PrimaryStorage.name          PostgreSQL Primary Storage      Contains the name of the       
                              Name                            PostgreSQL cluster to          
                                                              associate with this storage.   
                                                              Should match the Cluster name  
 PrimaryStorage.storageclass  PostgreSQL Primary              Contains the storage           
                              StorageClass                    class used for the primary     
                                                              PostgreSQL instance of the     
                                                              cluster                        
 PrimaryStorage.accessmode    PostgreSQL Primary              The access mode for            
                              StorageClass Access Mode        the storage class, e.g.        
                                                              "ReadWriteOnce"                
 PrimaryStorage.size          PostgreSQL Primary Data PVC     The size of the PVC that will  
                              Size                            store the data for the primary 
                                                              PostgreSQL instance, e.g. "1G" 
 status                       Deprecated                      Deprecated                     
 userlabels                   User defined labels             A set of labels that help the  
                                                              PostgreSQL Operator manage a   
                                                              PostgreSQL cluster      
```

## Expected behavior

show all possible parameters.

If I check example on https://operatorhub.io/operator/postgresql I can see that there are fields in CR that don't show up in parameter list above. For example `user` is parameter is not there
```yaml
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: hippo
  name: hippo
  labels:
    crunchy-pgha-scope: hippo
    deployment-name: hippo
    name: hippo
    namespace: pgo
    pg-cluster: hippo
    pgo-version: 4.7.0
spec:
  name: hippo
  namespace: pgo
  clustername: hippo
  ccpimage: crunchy-postgres-ha
  ccpimagetag: centos8-13.3-4.7.0
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ''
    name: ''
    size: 5Gi
    storageclass: ''
    storagetype: dynamic
    supplementalgroups: ''
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ''
    name: hippo
    size: 5Gi
    storageclass: ''
    storagetype: dynamic
    supplementalgroups: ''
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ''
    name: ''
    size: 5Gi
    storageclass: ''
    storagetype: dynamic
    supplementalgroups: ''
  database: hippo
  exporterport: '9187'
  pgbadgerport: '10000'
  podAntiAffinity:
    default: preferred
  port: '5432'
  user: hippo
  userlabels:
    pgo-version: 4.7.0
```

Related issue: #4850
