### ISSUE TITLE
`odo link`: custom mappings

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#4937]
/kind user-story

## User Story
As an odo user I want to be able to define what information should be exposed by link  (`ServiceBinding`) without editing Operator CR.

## Acceptance Criteria 
- [ ] It should be possible to specify custom mappings using parameters in `odo link` command

## Implementation notes

exmaple of a `ServiceBinding` resource with mappings
```yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: multi-service-binding
spec:

  application:
    name: java-app
    group: apps
    version: v1
    resource: deployments

 services:
  - group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    name: db-demo  
    id: postgresDB

  mappings:
    - name: JDBC_URL
      value: 'jdbc:postgresql://{{ .postgresDB.status.dbConnectionIP }}:{{ .postgresDB.status.dbConnectionPort }}/{{ .postgresDB.status.dbName }}'
    - name: DB_USER
      value: '{{ .postgresDB.status.dbCredentials.user }}'
```

/kind user-story

**Comment by dharmit** [comment]
> I was thinking something like `odo link myservice --map JDBC_USER='{{ .postgresDB.status.dbCredentials.user }}'`

And just like with parameters (`odo service create -p param1=value1 -p param2=value2`), multiple `--map` flags to be used for each pair of mapping?


> Is `mappings` a way for the user to specify things that we usually put in `annotations`?

@kadel do you know about this? From the docs, it seems like `mappings` uses Go template to achieve the same functionality that we get when we set `annotations`.

**Comment by dharmit** [comment]
Scope:
- [ ] https://github.com/openshift/odo/issues/4937#issuecomment-965503446
- [ ] Don't bother about the validation. It should be added as-is
- [ ] Tests
- [ ] Documentation

**Comment by dharmit** [comment]
Trying to update the dependency is leading to errors I can't figure how to address:

<details>

<summary> go get github.com/redhat-developer/service-binding-operator@v1.0.0 </summary>

```sh
$ go get github.com/redhat-developer/service-binding-operator@v1.0.0
# github.com/redhat-developer/service-binding-operator/apis/webhooks
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/apis/webhooks/admission.go:41:19: invalid operation: req.AdmissionRequest.Operation == v1beta1.Create (mismatched types "k8s.io/api/admission/v1".Operation and v1beta1.Operation)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/apis/webhooks/admission.go:41:54: invalid operation: req.AdmissionRequest.Operation == v1beta1.Update (mismatched types "k8s.io/api/admission/v1".Operation and v1beta1.Operation)
# github.com/redhat-developer/service-binding-operator/controllers/crd
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/controllers/crd/crd_controller.go:174:11: cannot use r (type *CrdReconciler) as type reconcile.Reconciler in argument to controllerruntime.NewControllerManagedBy(mgr).For(&"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".CustomResourceDefinition{}).Complete:
	*CrdReconciler does not implement reconcile.Reconciler (wrong type for Reconcile method)
		have Reconcile(reconcile.Request) (reconcile.Result, error)
		want Reconcile(context.Context, reconcile.Request) (reconcile.Result, error)
# github.com/redhat-developer/service-binding-operator/controllers
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/controllers/common.go:57:26: cannot use r.ReconcilingObject() (type apis.Object) as type client.Object in argument to controllerruntime.NewControllerManagedBy(mgr).For:
	apis.Object does not implement client.Object (missing GetAnnotations method)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/controllers/common.go:60:11: cannot use r (type *BindingReconciler) as type reconcile.Reconciler in argument to controllerruntime.NewControllerManagedBy(mgr).For(r.ReconcilingObject()).WithEventFilter(predicate.GenerationChangedPredicate{}).WithOptions(controller.Options{...}).Complete:
	*BindingReconciler does not implement reconcile.Reconciler (wrong type for Reconcile method)
		have Reconcile(reconcile.Request) (reconcile.Result, error)
		want Reconcile(context.Context, reconcile.Request) (reconcile.Result, error)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/controllers/common.go:81:23: cannot use serviceBinding (type apis.Object) as type client.Object in argument to r.Client.Get:
	apis.Object does not implement client.Object (missing GetAnnotations method)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/controllers/common.go:95:20: cannot use serviceBinding (type apis.Object) as type client.Object in argument to r.Client.Update:
	apis.Object does not implement client.Object (missing GetAnnotations method)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v1.0.0/controllers/common.go:108:22: cannot use serviceBinding (type apis.Object) as type client.Object in argument to r.Client.Update:
	apis.Object does not implement client.Object (missing GetAnnotations method)
```
</details>

I tried to update to the immediate next version and even that is failing:

<details>

<summary> go get github.com/redhat-developer/service-binding-operator@v0.9.1 </summary>

```sh
$ go get github.com/redhat-developer/service-binding-operator@v0.9.1
# github.com/redhat-developer/service-binding-operator/controllers
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v0.9.1/controllers/common.go:52:26: cannot use r.ReconcilingObject() (type apis.Object) as type client.Object in argument to controllerruntime.NewControllerManagedBy(mgr).For:
	apis.Object does not implement client.Object (missing GetAnnotations method)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v0.9.1/controllers/common.go:55:11: cannot use r (type *BindingReconciler) as type reconcile.Reconciler in argument to controllerruntime.NewControllerManagedBy(mgr).For(r.ReconcilingObject()).WithEventFilter(predicate.GenerationChangedPredicate{}).WithOptions(controller.Options{...}).Complete:
	*BindingReconciler does not implement reconcile.Reconciler (wrong type for Reconcile method)
		have Reconcile(reconcile.Request) (reconcile.Result, error)
		want Reconcile("context".Context, reconcile.Request) (reconcile.Result, error)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v0.9.1/controllers/common.go:72:23: cannot use serviceBinding (type apis.Object) as type client.Object in argument to r.Client.Get:
	apis.Object does not implement client.Object (missing GetAnnotations method)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v0.9.1/controllers/common.go:86:20: cannot use serviceBinding (type apis.Object) as type client.Object in argument to r.Client.Update:
	apis.Object does not implement client.Object (missing GetAnnotations method)
../../../../pkg/mod/github.com/redhat-developer/service-binding-operator@v0.9.1/controllers/common.go:99:22: cannot use serviceBinding (type apis.Object) as type client.Object in argument to r.Client.Update:
	apis.Object does not implement client.Object (missing GetAnnotations method)
```

</details>

I can't wrap my head around how we can fix these because the files mentioned in above outputs don't seem to be of odo code, but that of vendor'ed stuff. Any suggestions @feloy?

**Comment by feloy** [comment]
@dharmit It seems to be an incompatibility between the versions of `controller-runtime` used by odo vs `sbo`

**Comment by dharmit** [comment]
And SBO uses a pretty old version of it than odo. To move further, one thing I can think of is to see if multiple fields in `mappings` can be achieved using what we have in `go.mod` right now. Do you have any other ideas?

**Comment by kadel** [comment]
It looks like there were changes in SBOs Piplene handling our code will have to be updated to handle it

**Comment by kadel** [comment]
> I can't wrap my head around how we can fix these because the files mentioned in above outputs don't seem to be of odo code, but that of vendor'ed stuff. Any suggestions @feloy?

When something like this happens you can try following:
```
#  update version in go.mod manually to 1.0.0
go mod tidy
go mod vendor
make
```
You will see errors that might make more sense.

**Comment by kadel** [comment]
I completely forgot that we have `service_binding_builder.go` in odo code base. This is modified version for SBO to work around CRD permissions.  It will have to be updated as well.

**Comment by dharmit** [comment]
> To move further, one thing I can think of is to see if multiple fields in `mappings` can be achieved using what we have in `go.mod` right now.

I tried something along these lines. It's not working 100% because I seem to be making some mistake which I'm trying to figure. But I modified the `odo link` manifest between backend component & Postgres in the Quickstart guide to have mappings like below:

```yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  creationTimestamp: null
  name: backend-postgrescluster-hippo
spec:
  application:
    group: apps
    name: backend-app
    resource: deployments
    version: v1
  bindAsFiles: false
  detectBindingResources: true
  services:
  - group: postgres-operator.crunchydata.com
    kind: PostgresCluster
    name: hippo
    version: v1beta1
    id: postgresDb
  mappings:
    - name: EXAMPLE_MAPPING
      value: 'jdbc://{{ .hippo.observedGeneration }}:{{ .postgresDb.name }}'
status:
  secret: ""
```
What I'm seeing after `odo push` is:
```sh
$ odo exec -- env | grep EXAMPLE
EXAMPLE_MAPPING=jdbc://<no value>:<no value>
```
I'm doing something wrong which is leading to `<no value>` but multiple mappings part of things seem to work.

**Comment by dharmit** [comment]
> To move further, one thing I can think of is to see if multiple fields in `mappings` can be achieved using what we have in `go.mod` right now.

The reason I'm a little hopeful of this to work without updating SBO library is that [SBO docs](https://github.com/redhat-developer/service-binding-operator/blob/master/docs/userguide/modules/creating-service-bindings/pages/binding-options.adoc#compose-custom-binding-data) say it works for - "`ServiceBinding` in the `binding.operators.coreos.com` API group".

**Comment by dharmit** [comment]
It works without updating to a newer version, but there's a caveat in my observation - the docs say that the `id` field is optional, but without that field, it doesn't seem to work.

Taking our quickstart guide as example, I created the backend component and the service from [`postgrescluster.yaml` file](https://github.com/dharmit/odo-quickstart/blob/fc72b4fdaae7f6571cdef7a039ea1016c609cadc/postgrescluster.yaml). I then did `odo link PostgresCluster/hippo` and added `mappings` to `kubernetes/odo-service-backend-postgrescluster-hippo.yaml` as below:
```yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  creationTimestamp: null
  name: backend-postgrescluster-hippo
spec:
  application:
    group: apps
    name: backend-app
    resource: deployments
    version: v1
  bindAsFiles: false
  detectBindingResources: true
  services:
  - group: postgres-operator.crunchydata.com
    kind: PostgresCluster
    name: hippo
    version: v1beta1
    id: myid
  mappings:
    - name: EXAMPLE_MAPPING
      value: 'jdbc://{{ .myid.status.observedGeneration }}'
    - name: ANOTHER_MAPPING
      value: '{{ .myid.spec.image }}------$$$$$-----{{ .myid.spec.postgresVersion }}'
status:
  secret: ""
```
Here's the result after doing `odo push`:
```sh
$ odo exec -- env | grep -e "ANOTHER\|EXAMPLE"
EXAMPLE_MAPPING=jdbc://1
ANOTHER_MAPPING=registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0------$$$$$-----13
```
