### ISSUE TITLE
Collect monitoring logs from test VMs

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/odo#4993]
/kind user-story
/area testing

## User Story
As a QE we want to get VMs(where we are running tests like windows, mac etc) log so that whenever system gets unresponsive we figure out a reason of the failure and improve our systems.

## Acceptance Criteria 
- [x] Set up a monitoring job to collect logs from VMs
- [ ] It should collect VMs log
      - CPU 
      - Memory
      - Disk etc ...

## Links 
- Related issue: https://github.com/openshift/odo/issues/4938 

/kind user-story

**Comment by prietyc123** [comment]
Scope of the issue:

- [ ] Install exporter on the VMs. For linux we do `Node Exporter` whereas AFAIU `WMI` is the nice exporter for Windows servers
- [ ] make sure service(exporters) is running and started exposing the metrics
- [ ] Bind prometheus to exporters by modifying the prometheus config file with targets

Note: we have prometheus enabled in our IBM clusters.

**Comment by prietyc123** [comment]
> Bind prometheus to exporters by modifying the prometheus config file with targets https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html

It has dependency on ibm cloud cluster Admin credential. Currently we are facing issues with Admin user api access. @rnapoles-rh is working on that.

**Comment by prietyc123** [comment]
So far setup and configured monitoring for user-defined projects https://docs.openshift.com/container-platform/4.7/monitoring/enabling-monitoring-for-user-defined-projects.html on ibm cloud ocp cluster 4.7

**Comment by prietyc123** [comment]
- Created namespace `wmi-exporter` and given permissions for user to [view, edit monitoring](https://docs.openshift.com/container-platform/4.7/monitoring/enabling-monitoring-for-user-defined-projects.html#granting-user-permissions-using-the-cli_enabling-monitoring-for-user-defined-projects) 
- Create endpoints, service and servicemonitor crd for the VM https://gist.github.com/prietyc123/8cfe5ef63bf096abb3f3757849944c92
- Now I can see the job name configured inside the scrape_config file under prometheus route.
```
- job_name: wmi-exporter/windows-vm-metrics-monitor/0
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
[...]
```
However logs are not exposed to targets, may be due to some permission issue. I suspect it because
```
$ oc -n openshift-monitoring logs prometheus-k8s-0 -c prometheus|grep wmi

level=error ts=2021-09-07T23:12:11.099Z caller=klog.go:96 component=k8s_client_runtime func=
ErrorDepth msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:428: 
Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: 
User \"system:serviceaccount:openshift-monitoring:prometheus-k8s\" cannot list resource \"pods\" 
in API group \"\" in the namespace \"wmi-exporter\""
level=error ts=2021-09-07T23:12:38.683Z caller=klog.go:96 component=k8s_client_runtime func=
ErrorDepth msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:426: 
Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: 
User \"system:serviceaccount:openshift-monitoring:prometheus-k8s\" cannot list resource \"endpoints\" 
in API group \"\" in the namespace \"wmi-exporter\""
```
@kadel could you please help me in figuring out what am I missing here.

**Comment by prietyc123** [comment]
> ```
> $ oc -n openshift-monitoring logs prometheus-k8s-0 -c prometheus|grep wmi
> 
> level=error ts=2021-09-07T23:12:11.099Z caller=klog.go:96 component=k8s_client_runtime func=
> ErrorDepth msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:428: 
> Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: 
> User \"system:serviceaccount:openshift-monitoring:prometheus-k8s\" cannot list resource \"pods\" 
> in API group \"\" in the namespace \"wmi-exporter\""
> level=error ts=2021-09-07T23:12:38.683Z caller=klog.go:96 component=k8s_client_runtime func=
> ErrorDepth msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:426: 
> Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: 
> User \"system:serviceaccount:openshift-monitoring:prometheus-k8s\" cannot list resource \"endpoints\" 
> in API group \"\" in the namespace \"wmi-exporter\""
> ```

Fixed this permission failure with 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: wmi-exporter
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: wmi-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
```
Still endpoints are not exposing those metrics and my suspicion is its because of firewall restriction due to internal VM data extraction. I think this should get fixed once our VM move to IBM cloud. We will have the cluster and machine on the same cloud, so it should not be a problem.
