### ISSUE TITLE
How to pass env var to the buildConfig to be created when executing the command "odo create" ?

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#501]
The BuildConfig to be generated should be 

```
    source:
      git:
        uri: 'https://github.com/snowdrop/ocp-odo-build-install.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'openjdk18:latest'
        incremental: true
        env:
        - name: ARTIFACT_COPY_ARGS
          value: "*-exec.jar"
```
but `odo create` generates this one

```
  source:
    git:
      uri: 'https://github.com/snowdrop/ocp-odo-build-install.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk18:latest'
        namespace: openshift
    type: Source
```

So, How can we pass env var to the buildConfig to be created when executing the command "odo create" ?
