### ISSUE TITLE
Add support for composite run commands

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5054]
Odo currently doesn't support run commands that are composite.

- [ ] this needs to support `parallel` flag as well

simple example with composite run command for testing
```yaml
schemaVersion: 2.1.0
metadata:
  name: nodejs

components:
  - container:
      endpoints:
        - name: http-3000
          targetPort: 3000
      image: registry.access.redhat.com/ubi8/nodejs-14:latest
    name: runtime

commands:
  - id: install
    exec:
      commandLine: npm install
      component: runtime
      workingDir: /projects
  - id: start
    exec:
      workingDir: /projects
      commandLine: npm start
      component: runtime
  - id: run
    composite:
      commands:
        - install
        - start
      group:
        isDefault: true
        kind: run
```

/kind feature
/priority high
