### ISSUE TITLE
Build fails using odo create openjdk-1.8 command with parameter --binary

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#511]
According to the command doc, we can create a component and the buildConfig if we pass as parameter by example `--binary`

```
Examples:
  # Create new Node.js component with the source in current directory. 
  odo create nodejs

  # Create new Node.js component named 'frontend' with the source in './frontend' directory
  odo create nodejs frontend --local ./frontend

  # Create new Node.js component with source from remote git repository.
  odo create nodejs --git https://github.com/openshift/nodejs-ex.git

  # Create new Wildfly component with binary named sample.war in './downloads' directory
  odo create wildfly wildly --binary ./downloads/sample.war
```

Unfortunately, that will fail if we use this command as s2i build will use the python s2i docker image

```
odo create openjdk18 sb1 --binary ./target/ocp-fmp-build-install-1.0-exec.jar
...

Cloning "https://github.com/kadel/bootstrap-supervisored-s2i " ...
--
  | Commit:	66370523614e0873977d369378c62e8b0c49b28f (run assemble/run scripts  in source code .s2i direcotry)
  | Author:	Tomas Kral <tkral@redhat.com>
  | Date:	Tue Apr 24 15:53:25 2018 +0200
  | + set -eo pipefail
  | + PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/s2i
  | + HOME=/opt/app-root
  | + curl -s -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
  | + /usr/bin/python /tmp/get-pip.py --user
  | The directory '/opt/app-root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  | The directory '/opt/app-root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
  | Collecting pip
  | Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl  (1.3MB)
  | Collecting setuptools
  | Downloading https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl  (567kB)
  | Collecting wheel
  | Downloading https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl  (41kB)
  | Installing collected packages: pip, setuptools, wheel
  | Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/app-root'
  | Check the permissions.
  | error: build error: non-zero (13) exit code from registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift@sha256:aa51a265d9a1650c7371879b3f58b40987675aa80a589cafcadec360a71e63a6


```

BuildConfig fil;e generated is 

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.kubernetes.io/component-source-type: binary
    app.kubernetes.io/url: >-
      file:///Users/dabou/Temp/to-be-deleted/ocp-odo-build-install/target/ocp-fmp-build-install-1.0-exec.jar
  labels:
    app: odoapp
    app.kubernetes.io/component-name: sb1
    app.kubernetes.io/component-type: openjdk18
    app.kubernetes.io/name: odoapp
  name: sb1
  namespace: odo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'sb1:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: v0.0.1
      uri: 'https://github.com/kadel/bootstrap-supervisored-s2i'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk18:latest'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
```

I'm expecting that a SourceStream Binary strategy will be used here and not git as source.
