### ISSUE TITLE
Add support for ephemeral volumes.

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5131]
[Devfile 2.1.0](https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference.html) introduced new field in `volume` components called `ephemeral`

When `ephemeral: true` the volume should be always created as `emptyDir`

```
- name: volume-test
  volume:
    size: 1Gi
    ephemeral: true
```

/kind feature
/area devfile
/priority high
