### ISSUE TITLE
odo component describe without context fails

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/odo#5245]
/kind bug

## What versions of software are you using?

**Operating System:**
RHEL 8

**Output of `odo version`:**
odo v2.4.2 (88e89104e)

Server: https://api.sandbox.xyz.openshiftapps.com:6443
Kubernetes: v1.22.0-rc.0+ef241fd

## How did you run odo exactly?
created nodejs example component using IntelliJ plugin.
run odo describe command in commandline in home folder ( no context )
`odo component describe --project stephane-bouchet-dev --app app nodejs`

## Actual behavior
output failed with:
```
 ⚠  URLs couldn't not be retrieved: unable to list routes: the component name, the app name or both are empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x263c7a5]

goroutine 1 [running]:
github.com/openshift/odo/pkg/envinfo.(*EnvInfo).ListStorage(0xc000931d70, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/envinfo/storage.go:149 +0xa5
github.com/openshift/odo/pkg/component.(*ComponentFullDescription).loadStoragesFromClientAndLocalConfig(0xc000358b00, 0xc00086e510, 0x3603638, 0xc000931d40, 0x7fff5198e78d, 0x6, 0x7fff5198e789, 0x3, 0xc0003d06c0, 0x0, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component_full_description.go:73 +0x103
github.com/openshift/odo/pkg/component.NewComponentFullDescriptionFromClientAndLocalConfigProvider(0xc00086e510, 0xc000931d40, 0x7fff5198e78d, 0x6, 0x7fff5198e789, 0x3, 0x7fff5198e76e, 0x14, 0xc00005c0c4, 0x38, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component_full_description.go:199 +0x905
github.com/openshift/odo/pkg/odo/cli/component.(*DescribeOptions).Run(0xc00000e1b0, 0xc0000d8780, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:68 +0x9b
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x35c0410, 0xc00000e1b0, 0xc0000d8780, 0xc0000bcff0, 0x1, 0x5)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:97 +0x479
github.com/openshift/odo/pkg/odo/cli/component.NewCmdDescribe.func1(0xc0000d8780, 0xc0000bcff0, 0x1, 0x5)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:96 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0000d8780, 0xc0000bcfa0, 0x5, 0x5, 0xc0000d8780, 0xc0000bcfa0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000985680, 0xc00005e110, 0x2ec1ec0, 0x49a2488)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:890
main.main()
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:70 +0x426
```

## Expected behavior
should be possible to have the correct description like
```
Component Name: nodejs
Type: nodejs
Environment Variables:
 · PROJECTS_ROOT=/project
 · PROJECT_SOURCE=/project
 · DEBUG_PORT=5858
Storage:
 · m1 of size 1Gi mounted to /tmp
URLs:
 · http://http-3000-app-stephane-bouchet-dev.apps.sandbox.x8i5.p1.openshiftapps.com exposed via 3000

```

**Comment by valaparthvi** [comment]
Was this functional before? Were we able to run `odo describe` without the context folder?

**Comment by valaparthvi** [comment]
This case will definitely fail if the component is not pushed, and no context directory is passed, but we can definitely fix this panic in such a case.

**Comment by valaparthvi** [comment]
> Was this functional before? Were we able to run `odo describe` without the context folder?

Okay, so this used to work. I can confirm for v2.3.0, but it can use some improvement.

**Comment by valaparthvi** [comment]
I was discussing this with @dharmit, and he is of the opinion that ideally `odo describe` is a component specific command, and should only be run either with `--context`, or inside the context directory so that we can correctly describe the component and its related data while making use of both the devfile, and in-cluster data to decide on the state of them.

There are discrepancies between the `odo decribe` output for a pushed component when run within the context directory(or with --context), and outside the context directory without the --context flag. We cannot clearly define the state of storage, and urls, they could be locally deleted, but available on the cluster, or vice versa without having access to both devfile(local) and in-cluster(remote) data. We(Dharmit, and I) are not sure if it would be a good idea to have this difference between the 2 outputs.
(I'll put up sample outputs in the following 2 comments).

@sbouchet We would like to know your use case. Why did you have the need to run `odo describe` without the context flag/outside the context directory? If there is a valid use case, it would help us better define the behavior of the command.

**Comment by valaparthvi** [comment]
Outside the context directory:
```yaml
{
	"kind": "Component",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"name": "mynode2",
		"namespace": "default",
		"creationTimestamp": null,
		"labels": {
			"app": "app",
			"app.kubernetes.io/instance": "mynode2",
			"app.kubernetes.io/managed-by": "odo",
			"app.kubernetes.io/managed-by-version": "v2.4.3",
			"app.kubernetes.io/name": "",
			"app.kubernetes.io/part-of": "app",
			"component": "mynode2"
		},
		"annotations": {
			"deployment.kubernetes.io/revision": "1",
			"odo.dev/project-type": "nodejs"
		}
	},
	"spec": {
		"app": "app",
		"type": "nodejs",
		"urls": {
			"kind": "List",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {},
			"items": [
				{
					"kind": "URL",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "mynode2-3030",
						"creationTimestamp": null
					},
					"spec": {
						"host": "mynode2-3030.192.168.59.101",
						"protocol": "http",
						"port": 3030,
						"secure": false,
						"kind": "ingress",
						"path": "/"
					},
					"status": {
						"state": ""
					}
				}
			]
		},
		"storages": {
			"metadata": {},
			"items": [
				{
					"kind": "Storage",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "store1",
						"creationTimestamp": null
					},
					"spec": {
						"size": "1Gi",
						"path": "/data",
						"containerName": "runtime"
					}
				}
			]
		},
		"env": [
			{
				"name": "PROJECTS_ROOT",
				"value": "/project"
			},
			{
				"name": "PROJECT_SOURCE",
				"value": "/project"
			},
			{
				"name": "DEBUG_PORT",
				"value": "5858"
			}
		]
	},
	"status": {
		"state": "Pushed"
	}
}
```

**Comment by valaparthvi** [comment]
Inside the context directory:
```yaml
{
	"kind": "Component",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"name": "mynode2",
		"namespace": "default",
		"creationTimestamp": null,
		"labels": {
			"app": "app",
			"app.kubernetes.io/instance": "mynode2",
			"app.kubernetes.io/managed-by": "odo",
			"app.kubernetes.io/managed-by-version": "v2.4.3",
			"app.kubernetes.io/name": "",
			"app.kubernetes.io/part-of": "app",
			"component": "mynode2"
		},
		"annotations": {
			"deployment.kubernetes.io/revision": "1",
			"odo.dev/project-type": "nodejs"
		}
	},
	"spec": {
		"app": "app",
		"type": "nodejs",
		"urls": {
			"kind": "List",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {},
			"items": [
				{
					"kind": "URL",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "mynode2-3030",
						"creationTimestamp": null
					},
					"spec": {
						"host": "mynode2-3030.192.168.59.101",
						"protocol": "http",
						"port": 3030,
						"secure": false,
						"kind": "ingress",
						"path": "/"
					},
					"status": {
						"state": "Pushed"
					}
				}
			]
		},
		"storages": {
			"kind": "List",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {},
			"items": [
				{
					"kind": "Storage",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "store1",
						"creationTimestamp": null
					},
					"spec": {
						"size": "1Gi",
						"path": "/data",
						"containerName": "runtime"
					},
					"status": "Pushed"
				}
			]
		},
		"env": [
			{
				"name": "PROJECTS_ROOT",
				"value": "/project"
			},
			{
				"name": "PROJECT_SOURCE",
				"value": "/project"
			},
			{
				"name": "DEBUG_PORT",
				"value": "5858"
			}
		]
	},
	"status": {
		"state": "Pushed"
	}
}
```
