### ISSUE TITLE
Be able to specify ingress class name and default backend when using odo url create

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5339]
/kind feature

<!--

Welcome! - We kindly ask you to:

  1. Fill out the issue template below 
  2. Use the Google group if you have a question rather than a bug or feature request.
  
The group is at: https://groups.google.com/forum/#!forum/odo-users

Thanks for understanding, and for contributing to the project!

-->

## Which functionality do you think we should add?

My edge case is as follows:

I use:
1. Create my component
2. `odo url create` to create the url at hostname `nodejs.k8s.land`
3. `odo push`

I then check my ingress:
```sh
~/test/nodejs-ex  master ✗                                                                                                                                                                                                                                                                                                                                        82d ⚑ ◒  ⍉
▶ k get ingress
NAME                 CLASS    HOSTS                ADDRESS        PORTS     AGE
duplicati            nginx    duplicati.k8s.land   192.168.1.92   80, 443   171m
http-8080-c7380bff   <none>   http-8080.k8s.land                  80        24s
```

And see that it has (unfortunately) not been given an address.

Obviously it's an issue with my cluster, and I know _exactly_ why. It's because with `nginx-ingress` and pretty much *any* implementation on bare metal (say a custom cluster at a data center, or something hosted on digital ocean) you must specify what ingress controller you are using. 

For example, in a standard Kubernetes yaml, you would specify: `ingressClassName: nginx` under Ingress. See the example from: https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myserviceb
spec:
  rules:
  - host: myserviceb.foo.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myserviceb
            port:
              number: 80
  ingressClassName: nginx
```

So I describe the ingress and see:

```sh
▶ k describe ingress http-8080-c7380bff
Name:             http-8080-c7380bff
Labels:           app=app
                  app.kubernetes.io/instance=nodejs-nodejs-ex-grdf
                  app.kubernetes.io/managed-by=odo
                  app.kubernetes.io/managed-by-version=v2.5.0
                  app.kubernetes.io/part-of=app
                  odo.openshift.io/url-name=http-8080
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                Path  Backends
  ----                ----  --------
  http-8080.k8s.land  
                      /   nodejs-nodejs-ex-grdf-app:8080 (10.244.0.44:8080)
Annotations:          <none>
Events:               <none>
```

So yup, I need to specify the back-end.

To do that, I need to edit the yaml on k8s and add `ingressClassName: "nginx"`

Once I do that, I check my output and yay! an IP!:

```sh
~/test/nodejs-ex  master ✗                                                                                                                                                                                                                                                                                                                                        82d ⚑ ◒  ⍉
▶ k get ingress
NAME                 CLASS   HOSTS                ADDRESS        PORTS     AGE
duplicati            nginx   duplicati.k8s.land   192.168.1.92   80, 443   174m
http-8080-c7380bff   nginx   http-8080.k8s.land   192.168.1.92   80        4m2s
```

But it still doesn't work..

And that's because we also need to add the following to the yaml for specifying the default back end:

```yaml
  defaultBackend:
    service:
      name: nodejs-nodejs-ex-grdf-app
      port:
        number: 8080
```

As described here on the nginx issues list: https://github.com/nginxinc/kubernetes-ingress/issues/966

## Why is this needed?

So essentially, in order to get *ANY* bare metal support implemented with nginx-ingress, we must somehow implement these 2 features in order to deploy a url on bare metal.

And these two features being the following YAML in a k8s ingress:

```yaml
  ingressClassName: nginx
  defaultBackend:
    service:
      name: nodejs-nodejs-ex-grdf-app
      port:
        number: 8080
```
