### ISSUE TITLE
Fix discrepancies in `odo describe` machine readable and human readable output

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#5344]
There are discrepancies between the `odo decribe` output for a pushed component when run within the context directory(or with --context), and outside the context directory without the --context flag. We cannot clearly define the state of storage, and urls, they could be locally deleted, but available on the cluster, or vice versa without having access to both devfile(local) and in-cluster(remote) data. 

<details>
<summary>Outside the context directory:</summary>

```yaml
{
	"kind": "Component",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"name": "mynode2",
		"namespace": "default",
		"creationTimestamp": null,
		"labels": {
			"app": "app",
			"app.kubernetes.io/instance": "mynode2",
			"app.kubernetes.io/managed-by": "odo",
			"app.kubernetes.io/managed-by-version": "v2.4.3",
			"app.kubernetes.io/name": "",
			"app.kubernetes.io/part-of": "app",
			"component": "mynode2"
		},
		"annotations": {
			"deployment.kubernetes.io/revision": "1",
			"odo.dev/project-type": "nodejs"
		}
	},
	"spec": {
		"app": "app",
		"type": "nodejs",
		"urls": {
			"kind": "List",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {},
			"items": [
				{
					"kind": "URL",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "mynode2-3030",
						"creationTimestamp": null
					},
					"spec": {
						"host": "mynode2-3030.192.168.59.101",
						"protocol": "http",
						"port": 3030,
						"secure": false,
						"kind": "ingress",
						"path": "/"
					},
					"status": {
						"state": ""
					}
				}
			]
		},
		"storages": {
			"metadata": {},
			"items": [
				{
					"kind": "Storage",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "store1",
						"creationTimestamp": null
					},
					"spec": {
						"size": "1Gi",
						"path": "/data",
						"containerName": "runtime"
					}
				}
			]
		},
		"env": [
			{
				"name": "PROJECTS_ROOT",
				"value": "/project"
			},
			{
				"name": "PROJECT_SOURCE",
				"value": "/project"
			},
			{
				"name": "DEBUG_PORT",
				"value": "5858"
			}
		]
	},
	"status": {
		"state": "Pushed"
	}
}
```

</details>

<details>
<summary>Inside the context directory:</summary>

```yaml
{
	"kind": "Component",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"name": "mynode2",
		"namespace": "default",
		"creationTimestamp": null,
		"labels": {
			"app": "app",
			"app.kubernetes.io/instance": "mynode2",
			"app.kubernetes.io/managed-by": "odo",
			"app.kubernetes.io/managed-by-version": "v2.4.3",
			"app.kubernetes.io/name": "",
			"app.kubernetes.io/part-of": "app",
			"component": "mynode2"
		},
		"annotations": {
			"deployment.kubernetes.io/revision": "1",
			"odo.dev/project-type": "nodejs"
		}
	},
	"spec": {
		"app": "app",
		"type": "nodejs",
		"urls": {
			"kind": "List",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {},
			"items": [
				{
					"kind": "URL",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "mynode2-3030",
						"creationTimestamp": null
					},
					"spec": {
						"host": "mynode2-3030.192.168.59.101",
						"protocol": "http",
						"port": 3030,
						"secure": false,
						"kind": "ingress",
						"path": "/"
					},
					"status": {
						"state": "Pushed"
					}
				}
			]
		},
		"storages": {
			"kind": "List",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {},
			"items": [
				{
					"kind": "Storage",
					"apiVersion": "odo.dev/v1alpha1",
					"metadata": {
						"name": "store1",
						"creationTimestamp": null
					},
					"spec": {
						"size": "1Gi",
						"path": "/data",
						"containerName": "runtime"
					},
					"status": "Pushed"
				}
			]
		},
		"env": [
			{
				"name": "PROJECTS_ROOT",
				"value": "/project"
			},
			{
				"name": "PROJECT_SOURCE",
				"value": "/project"
			},
			{
				"name": "DEBUG_PORT",
				"value": "5858"
			}
		]
	},
	"status": {
		"state": "Pushed"
	}
}
```

</details>

_Originally posted by @valaparthvi in https://github.com/redhat-developer/odo/issues/5245#issuecomment-1001400170_

Apart from this, there are 2 structs at play here, [ComponentFullDescriptionSpec](https://github.com/redhat-developer/odo/blob/main/pkg/component/component_full_description.go#L22) vs [ComponentSpec](https://github.com/redhat-developer/odo/blob/main/pkg/component/types.go#L22), which are almost similar, except for a few fields.
