### ISSUE TITLE
Odd issue when using a name for a url creation when there is already a route in the devfile.yaml

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5387]
/kind bug

<!--

Welcome! - We kindly ask you to:

  1. Fill out the issue template below 
  2. Use the Google group if you have a question rather than a bug or feature request.

The group is at: https://groups.google.com/forum/#!forum/odo-users

Thanks for understanding, and for contributing to the project!

-->

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** odo v2.5.0 (724f16e68)


## How did you run odo exactly?

```
git clone https://github.com/odo-devfiles/odo-quickstart
cd odo-quickstart/frontend
odo create nodejs frontend
odo url create nodejs --port 3000 --host foo.com
odo push
```


## Actual behavior

```sh
/odo-quickstart/frontend  main ✗                                                                                                                                                                                                                                                                                                                                   119d ◒  
▶ odo push

Validation
 ✓  Validating the devfile [59588ns]

Creating Services for component frontend
 ✓  Services are in sync with the cluster, no changes are required

Creating Kubernetes resources for component frontend
 ✓  Waiting for component to start [8s]
 ✓  Links are in sync with the cluster, no changes are required
 ✓  Waiting for component to start [7ms]
 ⚠  Unable to create ingress, missing host information for Endpoint http-3000, please check instructions on URL creation (refer `odo url create --help`)

```

Why does it show a warning for the ingress of http-3000? 

If I am creating a URL with the same port, why is it added to the devfile.yaml rather than overriding the current one in there?

See the devfile.yaml output:

```yaml
components:
- container:
    dedicatedPod: false
    endpoints:
    - name: http-3000
      secure: false
      targetPort: 3000
    - exposure: public
      name: nodejs
      path: /
      protocol: http
      secure: false
      targetPort: 3000
    image: registry.access.redhat.com/ubi8/nodejs-14:latest
    memoryLimit: 1024Mi
    mountSources: true
    sourceMapping: /project
  name: runtime
```

## Expected behavior

Expected behaviour is to for the one within the devfile.yaml to be overridden, or atleast a warning come up when you use `odo url create`... it's very odd that it will just append to the devfile.yaml and not check what's already in there.


## Any logs, error output, etc?

See above
