### ISSUE TITLE
Unable to link a service to a component 

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5392]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** odo v2.5.0 (724f16e68)

## How did you run odo exactly?

Pretty major bug right now, because I'm unable to link a component *at all* and the error output does not show any relevant information.

```sh
git clone https://github.com/odo-devfiles/odo-quickstart
cd backend
odo create java-springboot backend
odo url create --port 8080 --host k8s.land
odo push
odo service create --from-file ../postgrescluster.yaml
odo push
odo link PostgresCluster/hippo
odo push

Validation
 ✓  Validating the devfile [179077ns]

Creating Services for component backend
 ✓  Created service "PostgresCluster/hippo" on the cluster; refer "odo link -h" to know how to link it to the component

Creating Kubernetes resources for component backend
 ✓  Waiting for component to start [10ms]
 ✗  Failed to start component with name "backend". Error: Failed to create the component: failed to create service(s) associated with the component: more than one item found in the result: [[<interface {} Value>] [-pguser-] [<interface {} Value>]]

```

## Actual behavior

See below:
```sh
odo push

Validation
 ✓  Validating the devfile [179077ns]

Creating Services for component backend
 ✓  Created service "PostgresCluster/hippo" on the cluster; refer "odo link -h" to know how to link it to the component

Creating Kubernetes resources for component backend
 ✓  Waiting for component to start [10ms]
 ✗  Failed to start component with name "backend". Error: Failed to create the component: failed to create service(s) associated with the component: more than one item found in the result: [[<interface {} Value>] [-pguser-] [<interface {} Value>]]
```

When you push, it is coming up with an odd error with that looks like a dump of interface / values from Go. 

## Expected behavior

Being able to link the service correctly.

## Any logs, error output, etc?

The output of the devfile is:

```yaml
commands:
- exec:
    commandLine: mvn clean -Dmaven.repo.local=/home/user/.m2/repository package -Dmaven.test.skip=true
    component: tools
    group:
      isDefault: true
      kind: build
    hotReloadCapable: false
  id: build
- exec:
    commandLine: mvn -Dmaven.repo.local=/home/user/.m2/repository spring-boot:run
    component: tools
    group:
      isDefault: true
      kind: run
    hotReloadCapable: false
  id: run
- exec:
    commandLine: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n
      -jar target/*.jar
    component: tools
    group:
      isDefault: true
      kind: debug
    hotReloadCapable: false
  id: debug
components:
- container:
    dedicatedPod: false
    endpoints:
    - name: 8080-tcp
      secure: false
      targetPort: 8080
    image: quay.io/eclipse/che-java11-maven:next
    memoryLimit: 768Mi
    mountSources: true
    volumeMounts:
    - name: m2
      path: /home/user/.m2
  name: tools
- name: m2
  volume:
    size: 3Gi
- kubernetes:
    uri: kubernetes/odo-service-hippo.yaml
  name: hippo
- kubernetes:
    uri: kubernetes/odo-service-backend-postgrescluster-hippo.yaml
  name: backend-postgrescluster-hippo
metadata:
  description: Spring Boot® using Java
  displayName: Spring Boot®
  globalMemoryLimit: 2674Mi
  icon: https://spring.io/images/projects/spring-edf462fec682b9d48cf628eaf9e19521.svg
  language: java
  name: backend
  projectType: spring
  tags:
  - Java
  - Spring
  version: 1.1.0
schemaVersion: 2.0.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/springboot-ex.git
  name: springbootproject
```
