### ISSUE TITLE
Linking a component will show an empty "Creating Services for component frontend"

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5399]
/kind bug

<!--

Welcome! - We kindly ask you to:

  1. Fill out the issue template below 
  2. Use the Google group if you have a question rather than a bug or feature request.

The group is at: https://groups.google.com/forum/#!forum/odo-users

Thanks for understanding, and for contributing to the project!

-->

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** 2.5

## How did you run odo exactly?

Follow the quick start guide and get to the point of linking the frontend and backend after creating a service.

https://odo.dev/docs/getting-started/quickstart


## Actual behavior

```sh
~/odo-quickstart/frontend  main ✗                                                                                                                                                                                                                                                                                                                                  121d ◒  ⍉
▶ odo push

Validation
 ✓  Validating the devfile [154004ns]

Creating Services for component frontend

Creating Kubernetes resources for component frontend
 ✓  Waiting for component to start [10ms]
 ✓  Links are in sync with the cluster, no changes are required
 ✓  Waiting for component to start [7ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component frontend
 ✓  Checking file changes for pushing [2ms]

Executing devfile commands for component frontend
 ✓  Executing install command "npm install" [1s]
 ✓  Executing run command "npm start" [1s]
```


## Expected behavior

Expected behaviour is to not have the "Creating SErvices for component frontend" line empty.


## Any logs, error output, etc?

devfile.yaml:

```yaml
commands:
- exec:
    commandLine: npm install
    component: runtime
    group:
      isDefault: true
      kind: build
    hotReloadCapable: false
    workingDir: /project
  id: install
- exec:
    commandLine: npm start
    component: runtime
    group:
      isDefault: true
      kind: run
    hotReloadCapable: false
    workingDir: /project
  id: run
- exec:
    commandLine: npm run debug
    component: runtime
    group:
      isDefault: true
      kind: debug
    hotReloadCapable: false
    workingDir: /project
  id: debug
- exec:
    commandLine: npm test
    component: runtime
    group:
      isDefault: true
      kind: test
    hotReloadCapable: false
    workingDir: /project
  id: test
components:
- container:
    dedicatedPod: false
    endpoints:
    - name: http-3000
      secure: false
      targetPort: 3000
    image: registry.access.redhat.com/ubi8/nodejs-14:latest
    memoryLimit: 1024Mi
    mountSources: true
    sourceMapping: /project
  name: runtime
- kubernetes:
    uri: kubernetes/odo-service-frontend-backend-app.yaml
  name: frontend-backend-app
metadata:
  description: Stack with Node.js 14
  displayName: Node.js Runtime
  icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg
  language: javascript
  name: frontend
  projectType: nodejs
  tags:
  - NodeJS
  - Express
  - ubi8
  version: 1.0.1
schemaVersion: 2.0.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/nodejs-ex.git
  name: nodejs-starter
```
