### ISSUE TITLE
using odo deploy - remote Dockerfile uri not accesible: HTTPS not supported

### ISSUE THREAD

**Issue by ajm01** [redhat-developer/odo#5450]
/kind bug

## What versions of software are you using?

**Operating System:**
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
**Output of `odo version`:**
```
 $ odo version
odo v2.5.0 (724f16e68)
```
## How did you run odo exactly?
`odo deploy` 
with the following deploy build component (and related commands) defined in the devfile:
```
  - name: outerloop-build-stack
    image:
       imageName: "{{container_image}}"
       dockerfile:
         uri: https://github.com/OpenLiberty/devfile-stack/releases/download/open-liberty-maven-0.8.1/Dockerfile
         buildContext: .
```
the dockerfile defined here is a stack dockerfile

## Actual behavior
```
$ odo deploy
 ✗  command execution failed: HTTP URL for uri is not supported
```

## Expected behavior
the remote stack provided dockerfile is retrieved and used to build the app image to be used for deployment
