### ISSUE TITLE
odo deploy - devfile variable substitution does not occur in uri referenced deployment manifest yaml file

### ISSUE THREAD

**Issue by ajm01** [redhat-developer/odo#5451]
/kind bug

## What versions of software are you using?

**Operating System:**
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
**Output of `odo version`:**
```
$ odo version
odo v2.5.0 (724f16e68)
```
## How did you run odo exactly?
`$ odo deploy`

with the following devfile variables defined:

```
variables:
  container_image: 'docker.io/ajymau/asi-outer-loop:app-provided'
  appname: 'test-inline'
```

and the following component (and related commands) defined:

```
  - name: myk8sdeploy
    kubernetes:
      uri: ./app-deploy.yaml
```

app-deploy.yaml contains substitution placeholders for the vars defined in the devfile:

```
apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: {{appname}}
spec:
  # Add fields here.
  applicationVersion: 1.0.0
  applicationImage: {{container_image}}
  service:
    type: ClusterIP
    port: 9080
    annotations:
      prometheus.io/scrape: 'true'
  probes:
    readiness:
      failureThreshold: 12
      httpGet:
        path: /health/ready
        port: 9080
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 1
    liveness:
      failureThreshold: 12
      httpGet:
        path: /health/live
        port: 9080
      initialDelaySeconds: 5
      periodSeconds: 2
  expose: true
  route:
    # Ingress required entries.
    pathType: 'Prefix'
    path: '/'
```

## Actual behavior
the app-deploy.yaml is used as is to do the deploy - no substitution occurs and the deploy fails because the names cannot be parsed:

```
$ odo deploy
.
.
..
173357979467: Layer already exists
app-provided: digest: sha256:40a963755d2202edf123e5868227dc64490a95302855ad20a9a607ced80d92f8 size: 4706
 ✗  command execution failed: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"appname":interface {}(nil)}
 $
```

## Expected behavior
variable substitution occurs first and the deploy occurs next, successfully

Note: if i inline the contents of app-deploy.yaml in the devfile the substitutions occur as expected. This should happen as well for a uri specified deployment manifest yaml.
