### ISSUE TITLE
2nd non-default deploy command defined in devfile causes odo to report error

### ISSUE THREAD

**Issue by ajm01** [redhat-developer/odo#5452]
/kind bug

## What versions of software are you using?

**Operating System:**
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
**Output of `odo version`:**
```
$ odo version
odo v2.5.0 (724f16e68)
```
## How did you run odo exactly?
`$ odo deploy`

with the following two deploy commands defined in the devfile:

```
  - id: deploy
    composite:
        commands:
          - build-image-stack-provided
          - outerloop-deploy
        group:
          kind: deploy
          isDefault: true
  - id: deploy-app-image
    composite:
       commands:
         - build-image-app-provided
         - outerloop-deploy
       group:
         kind: deploy
         isDefault: false
```
id: deploy is the default commands for the devfile and 
id: deploy-app-image is a second non-default command.

## Actual behavior
odo deply reports an error:

```
$ odo deploy
 ✗  more than one default deploy command found in devfile, should not happen
```

## Expected behavior
i expect to be able to call either:

`$ odo deploy`
or
`$odo deploy-app-image`

to have two slightly different build strategies occur as part of deploy.
