### ISSUE TITLE
Allow executing non-default deploy commands

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5454]
/kind user-story
/label v3
/priority medium

## User Story
As an odo user, I want to be able to execute alternative deploy command that is not marked as default So that I can run/test alternative deploy commands without editing `devfile.yaml`

## Acceptance Criteria 
- [ ] It should be possible to specify alternative deploy command via a flag on `odo deploy` command (for example `odo deploy --command altdeploy`

#### example 
```yaml
commands:
  - id: deploy
    composite:
        commands:
          - build-image-stack-provided
          - outerloop-deploy
        group:
          kind: deploy
          isDefault: true
  - id: deploy-app-image
    composite:
       commands:
         - build-image-app-provided
         - outerloop-deploy
       group:
         kind: deploy
         isDefault: false
```
- `odo deploy` should execute command `id: deploy`, because it is `kind: deploy` command marked with `isDefualt:true`
- `odo deploy --command deploy-app-image` should execute command `id: deploy-app-image`

## Links 
- user requested  in #5452

/kind user-story
