### ISSUE TITLE
Odo does not apply multiple deploy commands

### ISSUE THREAD

**Issue by yangcao77** [redhat-developer/odo#5480]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** odo v2.5.0 (2bd4f073e)

## How did you run odo exactly?
run `odo deploy` with a devfile having 2 deploy commands defined, one default, and one non-default. 
```
  - id: deploy
    composite:
        commands:
          - build-image-stack-provided
          - outerloop-deploy
        group:
          kind: deploy
          isDefault: true   
  # Deploy an app image built with a developer provided dockerfile - non-default action
  - id: deploy-app-image
    composite:
       commands:
         - build-image-app-provided
         - outerloop-deploy
       group:
         kind: deploy
```

## Actual behavior
Seeing error:
```
$ odo deploy
 ✗  more than one default deploy command found in devfile, should not happen
```
 
 However, I have one and only one default deploy command defined in devfile. 
 It is because Odo does not check for `isDefault` property, only checks for length of deploy commands.
https://github.com/redhat-developer/odo/blob/ce9506ded9ab9af822a6451278471fcc732cb268/pkg/devfile/adapters/kubernetes/component/adapter.go#L855-L860

## Expected behavior
Odo should allow multiple deploy commands, but only one `isDefault`
