### ISSUE TITLE
Use InitContainer to inject SupervisorD to container.

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#556]
## Problem
Right new we are using BuildConfig and https://github.com/kadel/bootstrap-supervisored-s2i to inject supervisor to s2i image.
This process is slow and creates unnecessary BuildConfig.

## Solution
Use initContainer and Go implementation of supervisor (https://github.com/ochinchina/supervisord)

InitContainer will copy supervisor binary with config file into the shared volume.
This volume is shared between initContainer and application container.

You can see an example of initContainer and volumes  approach at this small PoC - https://gist.github.com/kadel/35fa7c64c79a845edfe85ada2706019b

1) Create container image
    Image should include:
        - SupervisorD binary and config File. Config file should include one program definition that executes `run.sh` script. Something similar to current [run.conf](https://github.com/kadel/bootstrap-supervisored-s2i/blob/master/configs/supervisord.d/run.conf)
        - utility scripts that we are already using in our current approach  https://github.com/kadel/bootstrap-supervisored-s2i/tree/master/scripts
          Some of the scripts might need to be updated
    Image should be as small as possible
    Push that image somewhere where can be accessed by anyone (for example quay.io/odo/....)

    **Most of this work has already been done at https://github.com/snowdrop/k8s-supervisor/tree/master/supervisord. We should reuse that. It also includes small Go program to generate supervisord config file according to env parameters.**

2) update BootstrapSupervisoredS2I
   - BuildConfig is no longer needed.
   - DeploymentConfig should have new emptyDir volume (supervisor volume) that is mounted to the "application container" and initContainer
   -  modify initContainer
      initContainer should do two things:
        - copy files from /opt/app-root to the appRoot volume using `copy-files-to-volume` script (this is what it is currently doing)
         - copy supervisorD binary and config file to the supervisor volume 

3) make necessary changes to `component.Update`  function to make `odo update` work with new implementation

Change will impact local and binary components, git component will remain the same (with BuildConfig).

**Comment by cmoulliard** [comment]
Use case description and Tech spec of the solution is available [here](https://docs.google.com/document/d/1ordPK6sd5uEi8-_ARCdoDR0Ga82QMRiMLeLHPegljIE)
 
Solution to be merged in odo and tested with Spring Boot application where code was compiled as uber jar file is [available](https://github.com/cmoulliard/k8s-supervisor)

**Comment by cmoulliard** [comment]
> config file

When the initContainer will be started, then it will call a small go application to populate the content of the supervisord.conf using a list of CMDS passed as env var - [see](https://github.com/cmoulliard/k8s-supervisor/blob/master/supervisord/main.go#L39)

**Comment by cmoulliard** [comment]
> DeploymentConfig

Modifications to be done are available [here](https://github.com/cmoulliard/k8s-supervisor/blob/master/odo.go#L91-L137)

**Comment by cmoulliard** [comment]
> Supervisor config

it is not needed to start supervisord with the `run` command but instead to register the program with the option `autostart=false`

```
[program:run-java]
command = /usr/local/s2i/run
autostart = false
stdout_logfile=/dev/stdout
stdout_events_enabled=true

[program:compile-java]
command = /usr/local/s2i/assemble
autostart = false
stdout_logfile=/dev/stdout
stdout_events_enabled=true

[inet_http_server]
port=localhost:9001
```

Status
```
SB_POD=$(oc get pods -l app=spring-boot-supervisord -o name)
SERVICE_IP=$(minishift ip)

oc rsh $SB_POD /var/lib/supervisord/bin/supervisord ctl status
echo                             STOPPED   
run-java                        STOPPED   
compile-java                 STOPPED   
```

Next, when we call `odo push`, the code will copied or updated from the local file system of the developer to the pod and a rsh exec command executed to trigger one of the program

```
E.g
oc rsh $SB_POD /var/lib/supervisord/bin/supervisord ctl start run-java
run-java: started
oc rsh $SB_POD /var/lib/supervisord/bin/supervisord ctl start compile-java
compile-java: started
```

**Comment by slemeur** [comment]
@kadel : Should it be an epic?

**Comment by jorgemoralespou** [comment]
@kadel, are 2 initContainers required?

**Comment by cmoulliard** [comment]
@kadel @jorgemoralespou Another technical solution to be considered instead of managing the injection of the initContainer by odo is to delegate to k8s this responsability using a [webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/)

This is what servicemesh - istio [does](https://github.com/istio/istio/blob/0.8.0/install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml) 

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-sidecar-injector
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: {{ .Release.Namespace }}
        path: "/inject"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
```

where pods are matched using this rule

```
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
```

using a [configmap](https://github.com/istio/istio/blob/0.8.0/install/kubernetes/templates/istio-sidecar-injector-configmap-release.yaml.tmpl#L9) containing the definition about what should be changed/enriched

```

kind: ConfigMap
metadata:
  name: istio-inject
  namespace: {ISTIO_NAMESPACE}
apiVersion: v1
data:
  config: |
    policy: enabled
    template: |-
      initContainers:
...
```
