### ISSUE TITLE
add support for all command types to events

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5706]
currently the exec command is not supported in events

```
helm-install-postgresql should either map to an apply command or a composite command with apply commands
```

**Comment by kadel** [comment]
There was a discussion with a user who would require this to use odo and devfile in their environment.

The discussed use-case is using #6549 they would mount secrets like SSL certificates into the container, and then using `postStart` they would execute command to import SSL certs

**Comment by valaparthvi** [comment]
@kadel would you be able to provide a sample Devfile for this case?

**Comment by valaparthvi** [comment]
Note: We need to figure this out for podman as well.

**Comment by valaparthvi** [comment]
`preStart`, `postStop` events can only be an apply command or a composition of apply command.
`postStart`, and `preStop` can only be an exec command or composite exec command.

The above are Devfile limitations. 
https://github.com/redhat-developer/odo/blob/f9baeecbb56e9c8ad4e1fc08d6ecf987a50032e3/vendor/github.com/devfile/api/v2/pkg/validation/events.go#L27

**Comment by kadel** [comment]
I found another use-case where I was limited by lack of `exec` support in `preStart`.

I have nodejs project that requires yarn. I wanted to use Red Hat's `registry.access.redhat.com/ubi9/nodejs-18` image. But the image doesn't have Yarn. SO I wanted to do something like this 
```yaml

events:
  preStart:
    - install-yarn

commands:
  - id: install-yarn
    exec:
      commandLine: npm install -g yarn
      component: nodejs

  - id: run
    exec:
      commandLine: yarn run start
      component: nodejs
      group:
        kind: run
        isDefault: true
    
components:
  - name: nodejs
    container:
      image: registry.access.redhat.com/ubi9/nodejs-18:latest
      sourceMapping: /projects
      command: ['tail', '-f', '/dev/null']
```
