### ISSUE TITLE
Parsing problems with my devfile? Odd issues with schema validation

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5719]
/kind bug

<!--

Welcome! - We kindly ask you to:

  1. Fill out the issue template below 
  2. Use the Google group if you have a question rather than a bug or feature request.

The group is at: https://groups.google.com/forum/#!forum/odo-users

Thanks for understanding, and for contributing to the project!

-->

## What versions of software are you using?

**Operating System:** M1

**Output of `odo version`:** latest master

## How did you run odo exactly?

This is my devfile.yaml:

```yaml
commands:
- id: deploy
  composite:
    commands:
    - build-image
    - k8s-deployment
    - k8s-service
    group:
      kind: deploy
      isDefault: true
- id: build-image
  apply:
    component: outerloop-build
- id: k8s-deployment
  apply:
    component: outerloop-deployment
- id: k8s-service
  apply:
    component: outerloop-service
- exec:
    commandLine: npm install
    component: runtime
    group:
      isDefault: true
      kind: build
    workingDir: ${PROJECT_SOURCE}
  id: install
- exec:
    commandLine: npm start
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: ${PROJECT_SOURCE}
  id: run
- exec:
    commandLine: npm run debug
    component: runtime
    group:
      isDefault: true
      kind: debug
    workingDir: ${PROJECT_SOURCE}
  id: debug
- exec:
    commandLine: npm test
    component: runtime
    group:
      isDefault: true
      kind: test
    workingDir: ${PROJECT_SOURCE}
  id: test
components:
- name: outerloop-build
  image:
    dockerfile:
      buildContext: ${PROJECT_ROOT}
      rootRequired: false
      uri: ./Dockerfile
    imageName: "{{CONTAINER_IMAGE}}"
- name: outerloop-deployment
  kubernetes:
    inlined: |
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: my-node
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: node-app
        template:
          metadata:
            labels:
              app: node-app
          spec:
            containers:
              - name: my-node
                image: {{CONTAINER_IMAGE}}
                ports:
                  - name: http
                    containerPort: 3001
                    protocol: TCP
                resources:
                  limits:
                    memory: "1024Mi"
                    cpu: "500m"
- name: outerloop-service
  kubernetes:
    inlined: |
      apiVersion: v1
      kind: Service
      metadata:
        name: svc
      spec:
        ports:
        - name: "3000"
          port: 3000
          protocol: TCP
          targetPort: 3000
        selector:
          app: node-app
        type: ClusterIP
- name: runtime
  container:
    endpoints:
    - name: http-3000
      targetPort: 3000
    image: registry.access.redhat.com/ubi8/nodejs-14:latest
    memoryLimit: 1024Mi
    mountSources: true
metadata:
  description: Stack with Node.js 14
  displayName: Node.js Runtime
  icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg
  language: javascript
  name: my-nodejs-app
  projectType: nodejs
  tags:
  - NodeJS
  - Express
  - ubi8
  version: 1.0.1
schemaVersion: 2.0.0
variables:
  CONTAINER_IMAGE: quay.io/cdrage/test
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/nodejs-ex.git
  name: nodejs-starter
```

## Actual behavior

And when running `odo dev`, I get these errors:

```sh
k8s/devfiles/express  master ✗                                                                                                                                                                                                                                                                                                                                 63d4h ◒  ⍉
▶ odo dev
 ✗  unable to create context: failed to parse the devfile devfile.yaml, with error: failed to populateAndParseDevfile: invalid devfile schema. errors :
- (root): Additional property variables is not allowed
- commands.0.composite.group.kind: commands.0.composite.group.kind must be one of the following: "build", "run", "test", "debug"
- components.0: Must validate one and only one schema (oneOf)
- components.0: container is required
- components.0: Additional property image is not allowed
```

Despite the fact that the entire `devfile.yaml` was generated from `odo init`...

Any ideas? It seems like the schema checker is *really* wrong, including the variables section?

It's also trying to validate group.kind against "deploy" ?

## Expected behavior

Passing

## Any logs, error output, etc?
