### ISSUE TITLE
odo dev fails if multiple deployments exist for a component

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#5800]
Example devfile used for the project https://github.com/odo-devfiles/nodejs-ex:

<details>

<summary> devfile.yaml </summary>

```yaml
commands:
- exec:
    commandLine: npm install
    component: runtime
    group:
      isDefault: true
      kind: build
    workingDir: ${PROJECT_SOURCE}
  id: install
- exec:
    commandLine: npm start
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: ${PROJECT_SOURCE}
  id: run
- exec:
    commandLine: npm run debug
    component: runtime
    group:
      isDefault: true
      kind: debug
    workingDir: ${PROJECT_SOURCE}
  id: debug
- exec:
    commandLine: npm test
    component: runtime
    group:
      isDefault: true
      kind: test
    workingDir: ${PROJECT_SOURCE}
  id: test
components:
- container:
    endpoints:
    - name: http-3000
      targetPort: 3000
    image: registry.access.redhat.com/ubi8/nodejs-14:latest
    memoryLimit: 1024Mi
    mountSources: true
    command: ["tail"]
    args: ["-f", "/dev/null"]
  name: runtime
- name: infinitepodtwo
  kubernetes:  
    inlined: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: infinitepodtwo
      spec:
        containers:
          - name: blah
            image: docker.io/dharmit/infiniteloop
- name: infinitepodone
  kubernetes:  
    inlined: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: infinitepodone
      spec:
        containers:
          - name: blah
            image: docker.io/dharmit/infiniteloop
- name: mydeployment
  kubernetes:
    inlined: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: infinitedeployment
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: infinite
        template:
          metadata:
            labels:
              app: infinite
          spec:
            containers:
            - name: blah
              image: docker.io/dharmit/infiniteloop
metadata:
  description: Stack with Node.js 14
  displayName: Node.js Runtime
  icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg
  language: javascript
  name: node
  projectType: nodejs
  tags:
  - NodeJS
  - Express
  - ubi8
  version: 1.0.1
schemaVersion: 2.0.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/nodejs-ex.git
  name: nodejs-starter
```

</details>

First pass of `odo dev` works just fine. Modify `server.js` and save the file. `odo dev` which is watching the current working directory fails with:

```sh
$ odo dev
  __
 /  \__     Developing using the node Devfile
 \__/  \    Namespace: myproject
 /  \__/    odo version: v3.0.0-alpha2
 \__/

↪ Deploying to the cluster in developer mode
 ✓  Searching resource in cluster 
 ✓  Creating kind Pod [13ms]
 ✓  Searching resource in cluster 
 ✓  Creating kind Pod [15ms]
 ✓  Searching resource in cluster 
 ✓  Creating kind Deployment [13ms]
 ✓  Waiting for Kubernetes resources [3s]
 ✓  Syncing files into the container [158ms]
 ✓  Executing install command "npm install" on container "runtime" [2s]

Your application is now running on the cluster
 - Forwarding from 127.0.0.1:40001 -> 3000

Watching for changes in the current directory /home/dshah/src/nodejs-ex
Press Ctrl+c to exit `odo dev` and delete resources from the cluster


File /home/dshah/src/nodejs-ex/server.js changed
Pushing files...

Error occurred on Push - watch command was unable to push component: failed to create the component: unable to determine if component node exists: multiple Deployments exist for the selector: app.kubernetes.io/instance=node,app.kubernetes.io/managed-by=odo,app.kubernetes.io/part-of=app,odo.dev/mode=Dev. Only one must be present
```

/kind bug
/area dev
