### ISSUE TITLE
`odo dev`: Add support for non-exec commands part of a composite `run` or `debug` command

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#5832]
## User Story
- As an odo user
- Now that I am able to run commands that are composite (thanks to #5054)
- I want to be able to include non-exec commands(apply command) as part of my composite run or debug command
- So that I can perform additional operations, like applying other component definitions (e.g., for building and pushing images, creating other Kubernetes resources, ...)

## Acceptance Criteria 
- [ ] `odo dev` should run all the commands part of the composite `run` command
- [ ] `odo dev --debug` should run all the commands part of the composite `debug` command

## Example

```yaml
schemaVersion: 2.2.0
metadata:
  name: nodejs
variables:
  CONTAINER_IMAGE: quay.io/unknown-account/myimage

components:
  - container:
      endpoints:
        - name: http-3000
          targetPort: 3000
      image: registry.access.redhat.com/ubi8/nodejs-14:latest
    name: runtime

  - name: image-build-component
    image:
      imageName: "{{CONTAINER_IMAGE}}"
      dockerfile:
        uri: ./Dockerfile

  - name: my-k8s-resource
    kubernetes:
      # Resource potentially referencing the 'CONTAINER_IMAGE' variable.
      # Might be inlined as well.
      uri: 'k8s/my-resource.yaml'

commands:
  - id: build-image
    apply:
      component: image-build-component

  - id: create-k8s-resource
    apply:
      component: my-k8s-resource

  - id: install
    exec:
      commandLine: npm install
      component: runtime
      workingDir: /projects

  - id: start
    exec:
      workingDir: /projects
      commandLine: npm start
      component: runtime

  - id: run
    composite:
      commands:
        - build-image
        - create-k8s-resource
        - install
        - start
      group:
        isDefault: true
        kind: run
```

## Links 
- Related Epic (mandatory): 
- Blocked by: https://github.com/redhat-developer/odo/issues/5054

/kind user-story
