### ISSUE TITLE
Non odo components not reported

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#6007]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**

```
odo v3.0.0-beta2 (c8e4458f4)

Server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
Kubernetes: v1.23.5+9ce5071
```

## How did you run odo exactly?

Deploy a Quarkus app using ODC

`odo list`

## Actual behavior

Only odo components are reported

## Expected behavior

Non odo components should be reported

**Comment by kadel** [comment]
odo dones't have support for executing other than "deploy", "build", "run", "debug" commands
This is not a bug, but rather features that was not yet implemented

**Comment by feloy** [comment]
TODO(@feloy): Deploy from Openshift Developer Console to check what are the labels present in Deployment

**Comment by feloy** [comment]
Original issue: https://github.com/redhat-developer/odo/issues/4688

**Comment by feloy** [comment]
Labels on Deployment created by ODC:
```
  labels:
    app: code-with-quarkus
    app.kubernetes.io/component: code-with-quarkus
    app.kubernetes.io/instance: code-with-quarkus
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: code-with-quarkus
```

Labels on Deployment created by odo:

```
  labels:
    app: app
    app.kubernetes.io/instance: my-go-app
    app.kubernetes.io/managed-by: odo
    app.kubernetes.io/managed-by-version: v3.0.0-beta2
    app.kubernetes.io/part-of: app
    component: my-go-app
    odo.dev/mode: Dev
```

The ODC component appears if one adds the following label:
```
    app.kubernetes.io/managed-by: odc
```
