### ISSUE TITLE
odo dev does not react on devfile parent change

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6017]
/kind bug

## How did you run odo exactly?

The devfile references a parent devfile, and the devfile.yaml and parent.yaml are added to the gitignore file, so these files are not synced to the container.

```
// parent.yaml
commands:
- exec:
    commandLine: GOCACHE=${PROJECT_SOURCE}/.cache go build main.go
    component: runtime
    group:
      isDefault: true
      kind: build
    workingDir: ${PROJECT_SOURCE}
  id: build
- exec:
    commandLine: ./main
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: ${PROJECT_SOURCE}
  id: run
components:
- container:
    endpoints:
    - name: http
      targetPort: 8080
    image: quay.io/devfile/golang:latest
    memoryLimit: 1024Mi
    mountSources: true
  name: runtime
metadata:
  description: Stack with the latest Go version
  displayName: Go Runtime
  icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/golang.svg
  language: go
  name: my-go-app
  projectType: go
  tags:
  - Go
  version: 1.0.0
schemaVersion: 2.1.0
starterProjects:
- git:
    checkoutFrom:
      revision: main
    remotes:
      origin: https://github.com/devfile-samples/devfile-stack-go.git
  name: go-starter
```

```
// devfile.yaml
schemaVersion: 2.1.0
metadata:
  name: child
parent:
  uri: "parent.yaml"
```

```
// .gitignore
.odo/env
.odo/odo-file-index.json
.odo/devstate.json
main

/devfile.yaml
/parent.yaml
```

## Actual behavior

When the parent.yaml file is modified, odo dev does not react to the change.

## Expected behavior

odo dev should update the component with the changes done to the parent devfile.
