### ISSUE TITLE
Failed to delete the "ServiceBinding" resource: *my-resource* when `odo dev` finishes

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6054]
/kind bug

## What versions of software are you using?

**Operating System:**

Fedora Linux

**Output of `odo version`:**

odo v3.0.0-beta3 (27f9dff19)

## How did you run odo exactly?

devfile.yaml:

```
commands:
- exec:
    commandLine: GOCACHE=${PROJECT_SOURCE}/.cache go build main.go
    component: runtime
    group:
      isDefault: true
      kind: build
    hotReloadCapable: false
    workingDir: ${PROJECT_SOURCE}
  id: build
- exec:
    commandLine: ./main
    component: runtime
    group:
      isDefault: true
      kind: run
    hotReloadCapable: false
    workingDir: ${PROJECT_SOURCE}
  id: run
components:
- container:
    dedicatedPod: false
    endpoints:
    - name: http
      secure: false
      targetPort: 8080
    image: quay.io/devfile/golang:latest
    memoryLimit: 1024Mi
    mountSources: true
  name: runtime
- kubernetes:
    inlined: |
      apiVersion: binding.operators.coreos.com/v1alpha1
      kind: ServiceBinding
      metadata:
        creationTimestamp: null
        name: my-go-app-cluster-sample
      spec:
        application:
          group: apps
          kind: Deployment
          name: my-go-app-app
          version: v1
        bindAsFiles: true
        detectBindingResources: true
        services:
        - group: postgresql.k8s.enterprisedb.io
          id: my-go-app-cluster-sample
          kind: Cluster
          name: cluster-sample
          resource: clusters
          version: v1
      status:
        secret: ""
  name: my-go-app-cluster-sample
metadata:
  description: Stack with the latest Go version
  displayName: Go Runtime
  icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/golang.svg
  language: go
  name: my-go-app
  projectType: go
  tags:
  - Go
  version: 1.0.0
schemaVersion: 2.1.0
starterProjects:
- git:
    checkoutFrom:
      revision: main
    remotes:
      origin: https://github.com/devfile-samples/devfile-stack-go.git
  name: go-starter
```

```
odo dev
  __
 /  \__     Developing using the my-go-app Devfile
 \__/  \    Namespace: prj2
 /  \__/    odo version: v3.0.0-beta3
 \__/

↪ Deploying to the cluster in developer mode
 •  Waiting for Kubernetes resources  ...
 ✓  Creating kind ServiceBinding 
 ⚠  Pod is Pending
 ⚠  Pod is Terminating
 ⚠  No pod exists
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [267ms]
 ✓  Building your application in container on cluster (command: build) [2s]
 •  Executing the application (command: run)  ...
 -  Forwarding from 127.0.0.1:40001 -> 8080


Watching for changes in the current directory /home/phmartin/Documents/tests/go
Press Ctrl+c to exit `odo dev` and delete resources from the cluster

^C ✗  Dev mode interrupted by user
Cleaning resources, please wait
 ✗  Finished executing the application (command: run) [1m]
Failed to delete the "ServiceBinding" resource: my-go-app-cluster-sample
```

## Actual behavior

When odo dev terminates, this message apperas regularly, even if the servicebinding is correctly deleted.

## Expected behavior

The mesage should not appear.

## Any logs, error output, etc?

This happens because the servicebinding has an ownerref to the Deployment, which is (or can be, depending on the order the resources are deleted) deleted before the SB. In this case, the sb is deleted by garbage collection, and thus cannot be deleted by odo.
