### ISSUE TITLE
`odo init` - cloning wrong branch of starterProject 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6232]
/kind bug
```
▶ odo init  --name vertx  --devfile java-vertx --starter vertx-http-example-redhat
  __
 /  \__     Initializing a new component
 \__/  \
 /  \__/    odo version: v3.0.0-rc2
 \__/

 ✓  Downloading devfile "java-vertx" [1s]
 ✗  Downloading starter project "vertx-http-example-redhat" [2s]
 ✗  unable to download starter project "vertx-http-example-redhat": couldn't find remote ref "refs/heads/master"
the command failed, the devfile has been removed from current directory
```

default branch in https://github.com/openshift-vertx-examples/vertx-http-example-redhat is `main` but odo is trying to clone `master`.

inside devfile.yaml starter project is defined as this
```
  - name: vertx-health-checks-example-redhat
    git:
      remotes:
        origin: https://github.com/openshift-vertx-examples/vertx-health-checks-example-redhat
```
which is correct. If there is no `revision` defined it should use the default branch as defined in repository. It looks like odo is always assuming `master`.
