### ISSUE TITLE
`odo dev` and `odo remove binding` does not unbind the application and service properly; broken

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6270]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 34
**Output of `odo version`:**
odo v3.0.0
## How did you run odo exactly?
1.
```sh
odo init --starter go-starter --devfile go --name go-framework
```

<details>
<summary>2. Change the main.go file to the following.</summary>

```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"

	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go.mongodb.org/mongo-driver/mongo/readpref"
)

// Connection URI
var (
	USERNAME = os.Getenv("PERCONASERVERMONGODB_MONGODB_USER_ADMIN_USER")
	PASSWORD = os.Getenv("PERCONASERVERMONGODB_MONGODB_USER_ADMIN_PASSWORD")
	HOST     = os.Getenv("PERCONASERVERMONGODB_HOST")
	uri      = fmt.Sprintf("mongodb://%s:%s@%s:27017/?maxPoolSize=20&w=majority", USERNAME, PASSWORD, HOST)
)

func main() {
	http.HandleFunc("/", HelloServer)
	http.ListenAndServe("0.0.0.0:8080", nil)

}

func HelloServer(w http.ResponseWriter, r *http.Request) {
	// Create a new client and connect to the server
	client, err := mongo.Connect(context.TODO(), options.Client().ApplyURI(uri))

	if err != nil {
		fmt.Fprintf(w, "failed to connect to the server: %s", err.Error())
		return
	}
	defer func() {
		if err = client.Disconnect(context.TODO()); err != nil {
			fmt.Fprintf(w, "failed to disconnect: %s", err.Error())
			return
		}
	}()

	// Ping the primary
	if err := client.Ping(context.TODO(), readpref.Primary()); err != nil {
		fmt.Fprintf(w, "unable to connect to the server: %s", err.Error())
		return
	}
	fmt.Fprint(w, "Successfully pinged the server.")
}
```
</details>

3. Install SBO 1.3.1 and PerconaServerMongoDB 1.13.0 and wait for them both to install.
4. `odo set namespace my-percona-server-mongodb-operator`

<details>
<summary>5. Create mongodb service instance.</summary>

```yaml
apiVersion: psmdb.percona.com/v1-11-0
kind: PerconaServerMongoDB
metadata:
  name: mongodb-instance
spec:
  platform: openshift
  crVersion: 1.11.0
  image: percona/percona-server-mongodb:4.4.10-11
  allowUnsafeConfigurations: true
  upgradeOptions:
    apply: 4.4-recommended
    schedule: "0 2 * * *"
  secrets:
    users: mongo-cluster-secrets
  replsets:
  - name: rs0
    size: 1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
  sharding:
    enabled: true
    configsvrReplSet:
      size: 1
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
    mongos:
      size: 1
```
</details>

6. `odo add binding` and add the binding with mongodb. Does not matter how you bind.
7. `odo dev`
8. curl URL and should receive a 200 OK response.
9. `odo remove binding --name go-framework-mongodb-instance`
10. Wait for `odo dev` to finish its operations.
11. Check the pod for files or envvar. Check ServiceBinding resource.
## Actual behavior
ServiceBinding resource exists even after `odo remove binding` is executed.

## Expected behavior
ServiceBinding resource should have been deleted after `odo remove binding` is executed.

## Any logs, error output, etc?
This bug was produced on minikube(--driver=podman) v1.25.2.
Might be fixed by #6189
