### ISSUE TITLE
devfile with 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6280]
/kind bug

## What versions of software are you using?

**Output of `odo version`:**
odo v3.2.0 (8c2c63375)

Server: https://api.crc.testing:6443
Kubernetes: v1.24.0+3882f8f

## How did you run odo exactly?

```
▶ odo init  --devfile python-django --starter django-example --name pythontest
  __
 /  \__     Initializing a new component
 \__/  \
 /  \__/    odo version: v3.2.0
 \__/

 ✓  Downloading devfile "python-django" [1s]
 ✓  Downloading starter project "django-example" [8s]

Your new component 'pythontest' is ready in the current directory.
To start editing your component, use 'odo dev' and open this folder in your favorite IDE.
Changes will be directly reflected on the cluster.

▶ odo dev --debug
  __
 /  \__     Developing using the "pythontest" Devfile
 \__/  \    Namespace: asdff
 /  \__/    odo version: v3.2.0
 \__/

↪ Deploying to the cluster in developer mode
 •  Waiting for Kubernetes resources  ...

 ✗  Syncing files into the container
Error occurred on Push - watch command was unable to push component: failed to validate devfile build and run commands: debug command is not valid: no debug command found in devfile

 ✗  Syncing files into the container
Error occurred on Push - watch command was unable to push component: failed to validate devfile build and run commands: debug command is not valid: no debug command found in devfile


```

## Actual behavior

odo fails to complain that there is no `debug` command.
but the devfile has one `debug` command.

```
  - id: debug
    exec:
      commandLine: 'pip install debugpy && export DEBUG_MODE=True && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} manage.py runserver 0.0.0.0:8000 --noreload --nothreading'
      workingDir: ${PROJECT_SOURCE}
      component: py-web
      group:
        kind: debug

```

The problem is that it not marked as default `isDefault:true` is missing in `group`.

The same problem is with `run` and `build` commands. If there is a single command that is not marked as default odo fails

## Expected behavior
If only one command of a given group, users should not need to mark is a default.
Odo should in this case assume that the single command in a group is also default.
