### ISSUE TITLE
Integration tests fail due to change in "nodeshift-starters/devfile-sample" repository

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/odo#6291]
A few hours ago, https://github.com/nodeshift-starters/devfile-sample/pull/19/ was merged into the nodeshift-starters/devfile-sample repo which causes the integration tests to fail with below:

```
Expected
      <string>: commands:
      - apply:
          component: image-build
        id: build-image
      - apply:
          component: kubernetes-deploy
        id: deployk8s
      - composite:
          commands:
          - build-image
          - deployk8s
          group:
            isDefault: true
            kind: deploy
        id: deploy
      components:
      - image:
          dockerfile:
            buildContext: .
            rootRequired: false
            uri: Dockerfile
          imageName: nodejs-image:latest
        name: image-build
      - attributes:
          deployment/container-port: 3001
          deployment/cpuLimit: 100m
          deployment/cpuRequest: 10m
          deployment/memoryLimit: 100Mi
          deployment/memoryRequest: 50Mi
          deployment/replicas: 1
        kubernetes:
          endpoints:
          - name: http-3001
            path: /
            targetPort: 3001
          uri: deploy.yaml
        name: kubernetes-deploy
      metadata:
        attributes:
          alpha.dockerimage-port: 3001
        description: Stack with Node.js 16
        displayName: Node.js Runtime
        language: nodejs
        name: aname
        projectType: nodejs
        provider: Red Hat
        supportUrl: https://github.com/devfile-samples/devfile-support#support-information
        tags:
        - NodeJS
        - Express
        - ubi8
        version: 2.1.0
      parent:
        id: nodejs
        registryUrl: https://registry.devfile.io/
      schemaVersion: 2.2.0
      
  to contain substring
      <string>: outerloop-deploy
```

[Link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_odo/6166/pull-ci-redhat-developer-odo-main-v4.11-integration-e2e/1589846239099228160) to one of the failing tests.

/area testing
