### ISSUE TITLE
Tests failing due to Postgres operator 

### ISSUE THREAD

**Issue by anandrkskd** [redhat-developer/odo#6334]
/kind tests

Currently, odo tests require Postgres operator to test binding related features, 
but on openshift verison 4.12 postgres operator fails to work as expected 
- when using operatorhub.io edb postgres subscription
```
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: my-cloud-native-postgresql
    namespace: openshift-operators
  spec:
    channel: stable
    name: cloud-native-postgresql
    source: operatorhubio-catalog
    sourceNamespace: openshift-marketplace
```` 
it fails with crashloopbackoff for postgrespod

- when using redhat-certified subscription, it fails when we try to create a postgres cluster, ~due to PodSecurityAdmission~
Subscription:
```
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: my-cloud-native-postgresql
    namespace: openshift-operators
  spec:
    channel: stable
    name: cloud-native-postgresql
    source: certified-operators
    sourceNamespace: openshift-marketplac
```
cluster:
```
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  instances: 1
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
```

**Comment by kadel** [comment]
I just tried to create an instance of EDB PostgreSQL (v1.18) on 4.12 using webconsole and it worked ok. 

This is the cluster definition generated by web console that worked 
```yaml
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample
  namespace: openshift-operators
spec:
  logLevel: info
  startDelay: 30
  stopDelay: 30
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  enableSuperuserAccess: true
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: false
  minSyncReplicas: 0
  postgresGID: 26
  replicationSlots:
    highAvailability:
      slotPrefix: _cnp_
    updateInterval: 30
  primaryUpdateMethod: switchover
  postgresUID: 26
  walStorage:
    resizeInUseVolumes: true
    size: 1Gi
  maxSyncReplicas: 0
  switchoverDelay: 40000000
  storage:
    resizeInUseVolumes: true
    size: 1Gi
  primaryUpdateStrategy: unsupervised
  instances: 3

```

**Comment by kadel** [comment]
hmm, In fact using even the original definition works for me
```
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  instances: 1
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
```
