### ISSUE TITLE
`odo dev` cannot handle additional resources created for resources present in the Devfile

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6373]
/kind bug

<!--

Welcome! - We kindly ask you to:

  1. Fill out the issue template below 
  2. Use the Google group if you have a question rather than a bug or feature request.

The group is at: https://groups.google.com/forum/#!forum/odo-users

Thanks for understanding, and for contributing to the project!

-->

## What versions of software are you using?

**Operating System:**
Fedora 35
**Output of `odo version`:**
```sh
odo v3.3.0 (c71eb5118b)

Server: https://192.168.49.2:8443
Kubernetes: v1.23.3
```
## How did you run odo exactly?
1. Run init
```sh
odo init --devfile nodejs --name node --starter nodejs-starter
```
2. Replace the content of Devfile with the following.
<details>
<summary> Use this Devfile</summary>

```yaml
commands:
- exec:
    commandLine: npm install
    component: runtime
    group:
      isDefault: true
      kind: build
    workingDir: /project
  id: install
- exec:
    commandLine: npm start
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: /project
  id: run
- exec:
    commandLine: npm run debug
    component: runtime
    group:
      isDefault: true
      kind: debug
    workingDir: /project
  id: debug
- exec:
    commandLine: npm test
    component: runtime
    group:
      isDefault: true
      kind: test
    workingDir: /project
  id: test
- id: build-image
  apply:
    component: outerloop-build
# - id: deployk8s
#   apply:
#     component: outerloop-deploy
- id: deploy
  composite:
    commands:
      - build-image
      # - deployk8s
    group:
      kind: deploy
      isDefault: true
components:
- container:
    endpoints:
    - name: http-3000
      targetPort: 3000
    image: registry.access.redhat.com/ubi8/nodejs-14:latest
    memoryLimit: 1024Mi
    mountSources: true
    sourceMapping: /project
  name: runtime
- name: outerloop-build
  image:
    imageName: "{{CONTAINER_IMAGE}}"
    dockerfile:
      uri: ./Dockerfile
      buildContext: ${PROJECTS_ROOT}
      rootRequired: false
  
- name: outerloop-deploy
  kubernetes:
    inlined: |
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: my-component
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: node-app
        template:
          metadata:
            labels:
              app: node-app
          spec:
            containers:
              - name: main
                image: {{CONTAINER_IMAGE}}
                resources:
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
      ---
      kind: Service
      apiVersion: v1
      metadata:
        name: my-component-svc
      spec:
        ports:
        - name: http-8081
          port: 8081
          protocol: TCP
          targetPort: 8081
        selector:
          app: node-app

metadata:
  description: Stack with Node.js 14
  displayName: Node.js Runtime
  icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg
  language: javascript
  name: node
  projectType: nodejs
  tags:
  - NodeJS
  - Express
  - ubi8
  version: 1.0.1
schemaVersion: 2.2.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/nodejs-ex.git
  name: nodejs-starter
variables:
  CONTAINER_IMAGE: quay.io/unknown-account/myimage
```
</details>

3. Run `odo dev`.

## Actual behavior
`odo dev` deletes Endpoints and EndpointSlice created for the Service inside `outerloop-deploy` Devfile component because they are not present in the Devfile, even though their related Service is.

## Expected behavior
It should not try to delete the resources created for the service. It should be able to identify the resources associated with any resource present within the Devfile.

## Any logs, error output, etc?
<details>
<summary>Error Output:</summary>

```sh
$  odo dev                                                                                                                  
  __                                                                                                                                    
 /  \__     Developing using the "node" Devfile                                                                                         
 \__/  \    Namespace: default                                                                                                          
 /  \__/    odo version: v3.3.0                                                                                                         
 \__/                                                                                                                                   
                                                                                                                                        
↪ Deploying to the cluster in developer mode                                                                                            
 •  Waiting for Kubernetes resources  ...                                                                                               
 ✓  Creating resource Deployment/my-component                                                                                           
 ✓  Creating resource Service/my-component-svc                                                                                          
 ⚠  Pod is Pending                                                                                                                      
 ✓  Deleting resources not present in the Devfile: Endpoints/my-component-svc, EndpointSlice/my-component-svc-4ktwz [440ms]             
 ✓  Deleting resources not present in the Devfile: EndpointSlice/my-component-svc-4qgr7, Endpoints/my-component-svc [810ms]             
 ✓  Deleting resources not present in the Devfile: Endpoints/my-component-svc [497ms] 
 ✓  Deleting resources not present in the Devfile: Endpoints/my-component-svc, EndpointSlice/my-component-svc-qnpfx [550ms]
 ✓  Pod is Running
 ✓  Deleting resources not present in the Devfile: EndpointSlice/my-component-svc-8fmcv, Endpoints/my-component-svc [473ms]
 ✓  Syncing files into the container [274ms]
 ✓  Building your application in container on cluster (command: install) [3s]
 •  Executing the application (command: run)  ...
 -  Forwarding from 127.0.0.1:40001 -> 3000


↪ Dev mode
 Status:
 Watching for changes in the current directory /tmp/nodejs-demo

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
Pushing files...


File /tmp/nodejs-demo/.odo/devstate.json changed
 •  Waiting for Kubernetes resources  ...
 ✓  Deleting resources not present in the Devfile: Endpoints/my-component-svc, EndpointSlice/my-component-svc-qfswt [365ms]
 ✓  Syncing files into the container [20ms]

↪ Dev mode
 Status:
 Watching for changes in the current directory /tmp/nodejs-demo

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
 ✓  Deleting resources not present in the Devfile: Endpoints/my-component-svc [301ms]
 ✓  Deleting resources not present in the Devfile: Endpoints/my-component-svc, EndpointSlice/my-component-svc-jjs5d [378ms]
```
</details>
