### ISSUE TITLE
Support Image component for odo dev on podman

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6488]
/kind feature

## Which functionality do you think we should add?
`odo dev` on podman currently does not support building images from the devfile Image component.

## Why is this needed?
This feature can be useful if you require the built image for your containers, so a Devfile like below could use this feature.
<details>
<summary>devfile.yaml</summary>

```yaml
schemaVersion: 2.2.0
metadata:
  name: nodejs
variables:
  CONTAINER_IMAGE: quay.io/unknown-account/myimage

components:
  - container:
      endpoints:
        - name: http-3000
          targetPort: 3000
        - name: tcp-5858
          targetPort: 5858
      env:
      - name: DEBUG_PORT_PROJECT
        value: "5858"
      image: "{{CONTAINER_IMAGE}}"
    name: runtime

  - name: image-build-component
    image:
      imageName: "{{CONTAINER_IMAGE}}"
      dockerfile:
        uri: ./Dockerfile

commands:
  - id: build-image
    apply:
      component: image-build-component

  - id: install
    exec:
      commandLine: npm install
      component: runtime
      workingDir: /projects

  - id: start
    exec:
      workingDir: /projects
      commandLine: npm start
      component: runtime

  - id: build
    exec:
      commandLine: npm install
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: build

  - id: run
    composite:
      commands:
        - build-image
        - start
      group:
        isDefault: true
        kind: run
```
</details>
