### ISSUE TITLE
On Podman, unable to access local ports forwarded to container applications listening on the loopback interface (e.g. debug endpoints)

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6510]
/kind bug
/area dev
/area odo-on-podman

## What versions of software are you using?

**Operating System:**
Fedora 37, kernel 6.1.6-200.fc37.x86_64

**Output of `odo version`:**
`odo v3.5.0` (8dbf42e5e)

## How did you run odo exactly?

```
$ mkdir /tmp/nodejs && cd /tmp/nodejs
$ odo init --name debug-nodejs --devfile nodejs --starter nodejs-starter
$ ODO_EXPERIMENTAL_MODE=t odo dev --platform=podman --debug

...
 •  Executing the application (command: debug)  ...
 -  Forwarding from 127.0.0.1:40001 -> 3000
 -  Forwarding from 127.0.0.1:40002 -> 5858

...
```

As expected, trying to access the forwarded application port (40001 here) works correctly:
```
$ curl -i http://localhost:40001
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 39
ETag: W/"27-Jw3xdDamjf5jthPp3a/zd95HG0Y"
Date: Wed, 18 Jan 2023 15:04:06 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Hello from Node.js Starter Application!%
```

But trying to access the application on the forwarded debug port (40002 here) returns an error:
```
$ curl -i http://localhost:40002
curl: (56) Recv failure: Connection reset by peer
```

## Actual behavior
Accessing the application on the forwarded debug port (40002 here) returns an error:
```
$ curl -i http://localhost:40002
curl: (56) Recv failure: Connection reset by peer
```

## Expected behavior
When running `odo dev` against a cluster, we get the expected HTTP response from the forwarded application debug port:
```
$ curl -i http://localhost:40002
HTTP/1.0 400 Bad Request
Content-Type: text/html; charset=UTF-8

WebSockets request was expected
```

I was expecting the same behavior on Podman.

## Any logs, error output, etc?

<details>
<summary>podman kube generate</summary>

```yaml
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/debug-nodejs-app-runtime: container
    io.kubernetes.cri-o.SandboxID/debug-nodejs-app-runtime: 269e89e69b091b501843a3c29f0578568cd91f76496c92da296c57cef27c62c
    io.podman.annotations.autoremove/debug-nodejs-app-runtime: "FALSE"
    io.podman.annotations.init/debug-nodejs-app-runtime: "FALSE"
    io.podman.annotations.privileged/debug-nodejs-app-runtime: "FALSE"
    io.podman.annotations.publish-all/debug-nodejs-app-runtime: "FALSE"
  creationTimestamp: "2023-01-18T15:17:30Z"
  labels:
    app: debug-nodejs-app
  name: debug-nodejs-app
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - tail
    - -f
    - /dev/null
    env:
    - name: PROJECTS_ROOT
      value: /projects
    - name: DEBUG_PORT
      value: "5858"
    - name: PROJECT_SOURCE
      value: /projects
    image: registry.access.redhat.com/ubi8/nodejs-16:latest
    name: debug-nodejs-app-runtime
    ports:
    - containerPort: 3000
      hostPort: 40001
    - containerPort: 5858
      hostPort: 40002
    resources:
      limits:
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /projects
      name: odo-projects-debug-nodejs-app-pvc
    - mountPath: /opt/odo/
      name: odo-shared-data-debug-nodejs-app-pvc
  enableServiceLinks: false
  hostname: debug-nodejs-app
  restartPolicy: Always
  volumes:
  - name: odo-projects-debug-nodejs-app-pvc
    persistentVolumeClaim:
      claimName: odo-projects-debug-nodejs-app
  - name: odo-shared-data-debug-nodejs-app-pvc
    persistentVolumeClaim:
      claimName: odo-shared-data-debug-nodejs-app
status: {}
```

</details>

**Comment by rm3l** [comment]
🤔 Same behavior with the `java-springboot` Devfile and the `springbootproject` starter project.

**Comment by rm3l** [comment]
FWIW, I just discovered a `podman port` command and noticed we had several port mappings for each port. Not sure if it explains the issue, that said:

```
☸ kind-local-k8s-cluster in ~/w/t/6510-unable-to-access-the-forwarded-debug-port-of-the-node.js-starter-project-on-podman on  main [!] via ☕ v17.0.5 on ☁️   
$ podman port -a                        
aede5e4daea4    8080/tcp -> 0.0.0.0:40001
aede5e4daea4    5858/tcp -> 0.0.0.0:40002
bcafb172ed0b    8080/tcp -> 0.0.0.0:40001
bcafb172ed0b    5858/tcp -> 0.0.0.0:40002

☸ kind-local-k8s-cluster in ~/w/t/6510-unable-to-access-the-forwarded-debug-port-of-the-node.js-starter-project-on-podman on  main [!] via ☕ v17.0.5 on ☁️   
$ podman container ls                     
CONTAINER ID  IMAGE                                              COMMAND     CREATED        STATUS            PORTS                                             NAMES
aede5e4daea4  localhost/podman-pause:4.3.1-1668178887                        2 minutes ago  Up 2 minutes ago  0.0.0.0:40001->8080/tcp, 0.0.0.0:40002->5858/tcp  0ea0cc03a2fa-infra
bcafb172ed0b  registry.access.redhat.com/ubi8/openjdk-11:latest              2 minutes ago  Up 2 minutes ago  0.0.0.0:40001->8080/tcp, 0.0.0.0:40002->5858/tcp  debug-springboot-app-tools
```

**Comment by rm3l** [comment]
- Research if there are any other ways to expose ports on Podman (other than using hostPorts) that would work with apps listening on localhost
- If not, document this behavior as a difference between K8s and Podman. Add this to FAQ.

**Comment by rm3l** [comment]
**Summary of investigations**

Per https://github.com/containers/podman/issues/17353#issuecomment-1416319137, this behavior is intentional on Podman: applications that are bound to the loopback interface cannot be reached using `hostPort`.

I noticed we have the same issue when publishing ports with either Docker or Podman, e.g:
```shell
# On the host, localhost:20001 is reachable
$ docker container run --rm -p 20001:9000 -t quay.io/redhatworkshops/simple-python-web \
  /usr/bin/python3 -m http.server 9000 --bind 0.0.0.0

# On the host, localhost:20001 is not reachable
$ docker container run --rm -p 20001:9000 -t quay.io/redhatworkshops/simple-python-web \
  /usr/bin/python3 -m http.server 9000 --bind 127.0.0.1
```

Kubernetes port forwarding seems to work differently, according to the corresponding [design doc](https://docs.google.com/document/d/1OE_QoInPlVCK9rMAx9aybRmgFiVjHpJCHI9LrfdNM_s/edit#): it is currently specified in the [Container Runtime Interface (CRI)](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md). 
Before that, it used to be implemented by the [`kubelet` on the node](https://docs.google.com/document/d/1OE_QoInPlVCK9rMAx9aybRmgFiVjHpJCHI9LrfdNM_s/edit#heading=h.hjxla8rthggx) by using `nsenter` (to enter the network namespace) and `socat` (for the actual port-forwarding). 
This is also documented in the OpenShift docs: https://docs.openshift.com/container-platform/4.12/nodes/containers/nodes-containers-port-forwarding.html#nodes-containers-port-forwarding-about_nodes-containers-port-forwarding

Now, most CRI implementations I have seen (like [containerd](https://github.com/containerd/containerd/blob/main/pkg/cri/server/sandbox_portforward_linux.go#L60-L127) or [cri-o](https://github.com/cri-o/cri-o/blob/main/internal/oci/runtime_oci.go#L1225:22)) forward a stream inside the network namespace to a specific port.

For now, as agreed, I'm documenting this as a difference between K8s and Podman: users would need to explicitly bind their applications to 0.0.0.0 (or any public interfaces of the container) in such cases.

Meanwhile, I have explored alternatives that would not require users to change how they bind their applications to network interfaces:

1. Trying with a different network mode (like `pasta`, introduced in Podman 4.4), but this is not supported for `kube play` commands.
2. Trying creating a rootless network namespace and specifying it in the `podman kube play --net=ns:/proc/.../`, but again, this is not supported for `kube play` commands.
3. Trying something similar to the way Kubernetes does, using `socat`. For example:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    #ports:
    #- containerPort: 80
    #  hostPort: 8888
  - name: python-web-container
    image: quay.io/redhatworkshops/simple-python-web:latest
    command: [ '/usr/bin/python3', '-m', 'http.server', '9000', '--bind', '127.0.0.1']
    ports:
    - containerPort: 9000
      # This won't work
      hostPort: 19000
  
  - name: python-web-container-socat
    image: quay.io/devfile/base-developer-image:ubi8-latest
    command: [ '/bin/sh', '-c', 'socat -d -d tcp-listen:20002,reuseaddr,fork tcp:localhost:9000']
    ports:
    - containerPort: 20002
      # This works !
      hostPort: 20002

```
