### ISSUE TITLE
Research and define how can services  be linked to components

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#652]
With https://github.com/redhat-developer/odo/pull/413  odo can create services. 
But odo doesn't have an easy way to configure component so it is able to connect to the service.

- Research what is the standard way to connect to services created from a service catalog and how we can implement it.
- Define commands that will be used to connect services and components. We should use `odo link` command for it. Ideally, it should be as simple as running `odo link mysql` and `odo link mysql --component mycomponent`

**Comment by cmoulliard** [comment]
This is an interesting command `odo link`  that you propose to use to update the supervisord's deploymentConfig in order to add as `EnvFrom` the secret containing the parameters of a serviceInstance

We have implemented successfully this use case with the function `MountSecretAsEnvFrom(` - [see](https://goo.gl/DHFc2T)

From a functional point of view we do : 

- Search and get the DeploymentConfig to be enhanced
- Add `EnvFrom <- Secret generated during service binding
- Rollout the DeploymentConfig to have the Env vars available within the pod

The parameters that you should know will be the `secretName` created during `binding` step and the name of the `deploymentconfig` to be enhanced and optionally the namespace

**Comment by cmoulliard** [comment]
Command developed and code implemented to check if a secret exists like the component and next to add the `envFrom` to the container of the application

see - https://github.com/redhat-developer/odo/pull/723/files#diff-6025e9b620e9321c03c11bf29e5c4dbdR1435

**Comment by kadel** [comment]
> So the command could be
> 
> `odo link <name_of_the_component> --secret <secretName>`

The user doesn't have to know that it is a secret. From a users point of view, it should look like linking component to the service.
This might be better
`odo link <component_name> --service <service_name>`
On the background, it will be the same - finding the right Secret and injecting it to the component's DeploymentConfig.

We should also modify current `odo link` command that allows linking two components as `odo link <component_name_1> <component_name_2>` to `odo link <component_name_1> --component <component_name_2>`.

In general `odo link` command will have a following form `odo link <target_component> --<link_type> <source_component>`. Target component is optional and if not specified current component will be used.

Thoughts? @cmoulliard @jorgemoralespou

**Comment by cmoulliard** [comment]
As the information which is needed to link the secret to an application is available from the `serviceBinding` resource

```
 oc get servicebinding/dh-postgresql-apb -o yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 1
  name: dh-postgresql-apb
  namespace: cmoullia
apb
  uid: 91ee39ba-c19f-11e8-98df-0a580a800110
spec:
  externalID: 91ee3941-c19f-11e8-98df-0a580a800110
  instanceRef:
    name: dh-postgresql-apb // NAME OF THE SERVICE INSTANCE TO LOOK FOR
  parameters:
    postgresql_database: my_data
    postgresql_password: secret
    postgresql_user: luke
    postgresql_version: "9.6"
  secretName: dh-postgresql-apb // NAME OF THE SECRET TO USE TO CREATE ENVFROM IN DC
```

, then we can adopt your proposition

```
odo link <component_name> --service <service_name>
```
