### ISSUE TITLE
odo dev fails with unable push files to pod

### ISSUE THREAD

**Issue by stormshaun** [redhat-developer/odo#6611]
/kind bug

## What versions of software are you using?

`odo v3.7.0 (262d11e3e)`

**Operating System:**
Ubuntu 22.04

**Output of `odo version`:**
$ odo version
odo v3.7.0 (262d11e3e)

## How did you run odo exactly?
```
odo init --name java-maven --devfile java-maven --devfile-registry DefaultDevfileRegistry --starter springbootproject
odo dev

```

## Actual behavior
`Error occurred on Push - watch command was unable to push component: failed to sync to component with name java-maven: failed to sync to component with name java-maven: unable push files to pod: error while streaming command: command terminated with exit code 2`

## Expected behavior
Syncing successfully

## Any logs, error output, etc?

```
✗  Syncing files into the container [2s]

Error occurred on Push - watch command was unable to push component: failed to sync to component with name java-maven: failed to sync to component with name java-maven: unable push files to pod: error while streaming command: command terminated with exit code 2

 ◑  Syncing files into the container ✗  Command 'tar xf - -C /projects --no-same-owner' in container failed.

 ✗  stdout:

 ✗  stderr: tar: devfile.yaml: Cannot open: Permission denied
tar: src: Cannot mkdir: Permission denied
tar: src/main/java/com/example/demo/DemoApplication.java: Cannot open: No such file or directory
tar: mvnw.cmd: Cannot open: Permission denied
tar: src: Cannot mkdir: Permission denied
tar: src/test/java/com/example/demo/DemoApplicationTests.java: Cannot open: No such file or directory
tar: pom.xml: Cannot open: Permission denied
tar: mvnw: Cannot open: Permission denied
tar: .gitignore: Cannot open: Permission denied
tar: HELP.md: Cannot open: Permission denied
tar: src: Cannot mkdir: Permission denied
tar: src/main/resources/application.properties: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors


 ✗  err: error while streaming command: command terminated with exit code 2
```

**Comment by rm3l** [comment]
Hi @stormshaun !
Thanks for reporting this issue.
Which kind of cluster are you using? We have similar issues reported when using `odo` on EKS (https://github.com/redhat-developer/odo/issues/6588) or AKS (https://github.com/redhat-developer/odo/issues/6585).

**Comment by rm3l** [comment]
> > Hi @stormshaun ! Thanks for reporting this issue. Which kind of cluster are you using? We have similar issues reported when using `odo` on EKS (#6588) or AKS (#6585).
> 
> Hi @rm3l - We are experiencing this on OCP and also on ARO

Thanks for the info.
Can you please run `odo preference set Ephemeral true` prior to running `odo dev`, to see if it fixes the issue? Thanks.

**Comment by stormshaun** [comment]
> > > Hi @stormshaun ! Thanks for reporting this issue. Which kind of cluster are you using? We have similar issues reported when using `odo` on EKS (#6588) or AKS (#6585).
> 
> > 
> 
> > Hi @rm3l - We are experiencing this on OCP and also on ARO
> 
> 
> 
> Thanks for the info.
> 
> Can you please run `odo preference set Ephemeral true` prior to running `odo dev`, to see if it fixes the issue? Thanks.

Thank you @rm3l, I'll try

Would you mind briefly sharing what the command does
`odo preference set Ephemeral true`

**Comment by rm3l** [comment]
> 
> Would you mind briefly sharing what the command does `odo preference set Ephemeral true`

Sure! We suspect an issue with persistent volumes.
So with `Ephemeral` set to `true`, `odo` will not use a Persistent Volume Claim (PVC) to store source code and sync files, but an [`EmptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume instead.
The [default behavior](https://odo.dev/docs/overview/configure#preference-key-table) is to use PVCs, but we noticed similar issues depending on the storage class.

**Comment by stormshaun** [comment]
> Sure! We suspect an issue with persistent volumes. So with `Ephemeral` set to `true`, `odo` will not use a Persistent Volume Claim (PVC) to store source code and sync files, but an [`EmptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume instead. The [default behavior](https://odo.dev/docs/development/architecture/how-odo-works#project-sources) is to use PVCs, but we noticed similar issues depending on the storage class.

Hi @rm3l - Thank you! I was able to proceed after setting up the preference. If I  understand correctly, the issue lies between odo and PVC and not specifically in the cluster, as it looks like to be occurring across multiple platforms (EKS, AKS, OCP, ARO) and the work on `odo` side is in the board to address this behavior

**Comment by feloy** [comment]
Related: https://github.com/redhat-developer/odo/issues/5093

**Comment by valaparthvi** [comment]
Another solution is setting `sourceMapping` inside your container and then using `${PROJECT_SOURCE}` wherever the need be, in this case instead of mounting `m2` on `/home/user/.m2`, you mount it on `${PROJECT_SOURCE}/.m2` and then change the build command to also use the same.

<details><summary>So your final devfile will look something like this</summary>
<p>

```yaml
commands:
- exec:
    commandLine: mvn -Dmaven.repo.local=${PROJECT_SOURCE}/.m2/repository package   #<---- 
    component: tools
    group:
      isDefault: true
      kind: build
    workingDir: ${PROJECT_SOURCE}
  id: mvn-package
- exec:
    commandLine: java -jar target/*.jar
    component: tools
    group:
      isDefault: true
      kind: run
    workingDir: ${PROJECT_SOURCE}
  id: run
- exec:
    commandLine: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n
      -jar target/*.jar
    component: tools
    group:
      isDefault: true
      kind: debug
    workingDir: ${PROJECT_SOURCE}
  id: debug
components:
- container:
    command:
    - tail
    - -f
    - /dev/null
    endpoints:
    - name: http-maven
      targetPort: 8080
    - exposure: none
      name: debug
      targetPort: 5858
    env:
    - name: DEBUG_PORT
      value: "5858"
    image: registry.access.redhat.com/ubi8/openjdk-11:latest
    memoryLimit: 512Mi
    mountSources: true
    sourceMapping: something #<----- setting this will assign the value to $PROJECT_SOURCE
    volumeMounts:
    - name: m2
      path: ${PROJECT_SOURCE}/.m2     #<---- 
  name: tools
- name: m2
  volume: {}
metadata:
  description: Java application based on Maven 3.6 and OpenJDK 11
  displayName: Maven Java
  icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/java-maven.jpg
  language: Java
  name: java-maven
  projectType: Maven
  tags:
  - Java
  - Maven
  version: 1.2.0
schemaVersion: 2.1.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/springboot-ex.git
  name: springbootproject
```


</p>
</details>
