### ISSUE TITLE
Test if odo works with GKE (Google Kubernetes Engine)

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6706]
similarly to what has been done for AKS and EKS #6585 #6588

/kind task

**Comment by valaparthvi** [comment]
I'd like to work on this @kadel, if you don't mind.

**Comment by valaparthvi** [comment]
<details>
<summary>`odo dev` for a Go Devfile with Go starter project with Ephemeral=false fails while Syncing files</summary>
```sh
odo dev
  __
 /  \__     Developing using the "my-go-app" Devfile
 \__/  \    Namespace: restapi-mongodb
 /  \__/    odo version: v3.10.0
 \__/

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
Warning: Autopilot set default resource requests for Deployment restapi-mongodb/my-go-app-app, as resource requests were not specified. See http://g.co/gke/autopilot-defaults
 ⚠  Pod is Pending
 ✓  Pod is Running
 ◓  Syncing files into the container ✗  Command 'tar xf - -C /projects --no-same-owner' in container failed.

 ✗  stdout:

 ✗  stderr: tar: main.go: Cannot open: Permission denied
tar: .gitignore: Cannot open: Permission denied
tar: README.md: Cannot open: Permission denied
tar: devfile.yaml: Cannot open: Permission denied
tar: go.mod: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors


 ✗  err: error while streaming command: command terminated with exit code 2

 ✗  Syncing files into the container [7s]
Error occurred on Push - watch command was unable to push component: failed to sync to component with name my-go-app: failed to sync to component with name my-go-app: unable push files to pod: error while streaming command: command terminated with exit code 2


↪ Dev mode
 Status:
 Watching for changes in the current directory /tmp/nodejs-debug

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
```
</details>

It works well when

**Comment by valaparthvi** [comment]
<details><summary>`odo dev` for --devfile=java-springboot --starter=springbootproject Ephmeral=false fails because it could not find `/home/user/.m2/repository`; repository does not exist</summary>
<p>

```sh
odo dev
  __
 /  \__     Developing using the "springboot" Devfile
 \__/  \    Namespace: restapi-mongodb
 /  \__/    odo version: v3.10.0
 \__/

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
 ✓  Added storage m2 to component
Warning: Autopilot set default resource requests for Deployment restapi-mongodb/springboot-app, as resource requests were not specified. See http://g.co/gke/autopilot-defaults
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [7s]
 ✗  Building your application in container (command: build) [20s]
[ERROR] Could not create local repository at /home/user/.m2/repository -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
Error occurred on Push - watch command was unable to push component: unable to exec command [/bin/sh -c cd ${PROJECT_SOURCE} && (mvn clean -Dmaven.repo.local=/home/user/.m2/repository package -Dmaven.test.skip=true) 1>>/proc/1/fd/1 2>>/proc/1/fd/2]: error while streaming command: command terminated with exit code 1


↪ Dev mode
 Status:
 Watching for changes in the current directory /tmp/nodejs-debug-2

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
pPushing files...
```

</p>
</details>

**Comment by valaparthvi** [comment]
Another solution that might work is setting `sourceMapping` inside the Devfile container component and then use `${PROJECT_SOURCE}` wherever the need be, in case of a Java devfile, instead of mounting `m2` on `/home/user/.m2`, you mount it on `${PROJECT_SOURCE}/.m2` and then change the build command to also use the same.

For Go Devfile, I had to temporarily unset `GOPATH` and `GOCACHE` in the build command, because `${PROJECT_SOURCE}/.go` and `${PROJECT_SOURCE}/.cache` resulted in `something/.go` and `something/.cache` which is a relative path, and these env vars must always be an absolute path.

<details><summary>So your final java-maven devfile will look something like this</summary>
<p>

```yaml
commands:
- exec:
    commandLine: mvn -Dmaven.repo.local=${PROJECT_SOURCE}/.m2/repository package   #<---- 
    component: tools
    group:
      isDefault: true
      kind: build
    workingDir: ${PROJECT_SOURCE}
  id: mvn-package
- exec:
    commandLine: java -jar target/*.jar
    component: tools
    group:
      isDefault: true
      kind: run
    workingDir: ${PROJECT_SOURCE}
  id: run
- exec:
    commandLine: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n
      -jar target/*.jar
    component: tools
    group:
      isDefault: true
      kind: debug
    workingDir: ${PROJECT_SOURCE}
  id: debug
components:
- container:
    command:
    - tail
    - -f
    - /dev/null
    endpoints:
    - name: http-maven
      targetPort: 8080
    - exposure: none
      name: debug
      targetPort: 5858
    env:
    - name: DEBUG_PORT
      value: "5858"
    image: registry.access.redhat.com/ubi8/openjdk-11:latest
    memoryLimit: 512Mi
    mountSources: true
    sourceMapping: something #<----- setting this will assign the value to $PROJECT_SOURCE; this will mount your sources on $HOME/something directory to which the user has access
    volumeMounts:
    - name: m2
      path: ${PROJECT_SOURCE}/.m2     #<---- 
  name: tools
- name: m2
  volume: {}
metadata:
  description: Java application based on Maven 3.6 and OpenJDK 11
  displayName: Maven Java
  icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/java-maven.jpg
  language: Java
  name: java-maven
  projectType: Maven
  tags:
  - Java
  - Maven
  version: 1.2.0
schemaVersion: 2.1.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/springboot-ex.git
  name: springbootproject
```


</p>
</details>  


>The [default behavior](https://odo.dev/docs/development/architecture/how-odo-works#project-sources) is to use PVCs, but we noticed similar issues depending on the storage class.
Ref: https://github.com/redhat-developer/odo/issues/6611#issuecomment-1438564713

Like Armel said, this has to do with which storage provisioner you use. By default, GKE uses `pd.csi.storage.gke.io` which perhaps restricts a non-root user from accessing directories other than the $HOME directory. All the [images](https://github.com/devfile/developer-images/blob/main/base/ubi9/Dockerfile) used by Devfile stacks use a non-root user, in most cases _default_, in some cases _jboss_, but in all cases a non-root user; if your container image uses a root user, you would have a freer reign.
