### ISSUE TITLE
Variable substitution does not work in pod-overrides and container-overrides

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6764]
```yaml
components:
  - container:
      image: quay.io/tkral/devbox-demo-devbox
    attributes:
      pod-overrides:
        spec:
          serviceAccountName: "{{RESOURCE_NAME}}"
variables:
  RESOURCE_NAME: my-go-app
```

```sh
$ odo dev
 /  \__     Developing using the "restapi" Devfile
 \__/  \    Namespace: restapi-mongodb
 /  \__/    odo version: v3.9.0
 \__/

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
Cleaning resources, please wait
 ✗  unable to create or update component: unable to update Deployment restapi-app: Deployment.apps "restapi-app" is invalid: spec.template.spec.serviceAccountName: Invalid value: "{{RESOURCE_NAME}}": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

"{{RESOURCE NAME}}" should be replaced by "my-go-app", instead an error is returned.

This probably needs to be fixed on the devfile/library side.

/kind bug
/area devfile-spec
