### ISSUE TITLE
PodSecurity admission for `odo deploy` is ineffective if the container uses pod-overrides attribute

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6777]
/kind bug

## What versions of software are you using?

**Operating System:**
```
Linux fedora 6.0.12-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:53:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
**Output of `odo version`:**
```sh
odo v3.9.0 (b57d3e2f17)

Server: https://<server>:6443
Kubernetes: v1.26.3+379cd9f
```
## How did you run odo exactly?
```
git clone --branch outerloop-with-helm https://github.com/valaparthvi/restapi-mongodb-odo.git &&  cd restapi-mongodb-odo
```

```
odo deploy
```
## Actual behavior
```sh
$ odo deploy
  __
 /  \__     Running the application in Deploy mode using my-go-app Devfile
 \__/  \    Namespace: restapi-mongodb
 /  \__/    odo version: v3.9.0
 \__/

↪ Deploying Kubernetes Component: my-go-app
 ✓  Creating resource ServiceAccount/my-go-app 

↪ Deploying Kubernetes Component: my-go-app
 ✓  Creating resource Role/my-go-app 

↪ Deploying Kubernetes Component: my-go-app
 ✓  Creating resource RoleBinding/my-go-app 

↪ Executing command:
 ◐  Executing command in container (command: deploy-db)Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "deploy-db" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "deploy-db" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "deploy-db" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "deploy-db" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
 ◐  Executing command in container (command: deploy-db)
Tip: Run `odo logs --deploy --follow` to get the logs of the command output.
 ◓  Executing command in container (command: deploy-db)^C% 
```

```sh
$ k get po 
No resources found in restapi-mongodb namespace.
$ k get job
NAME                      COMPLETIONS   DURATION   AGE
my-go-app-app-deploy-db   0/1           98s        98s
```

The pod cannot be created because it does not satisfy pod security admission policies.

## Expected behavior
It should create the pod and complete the job.

**Comment by valaparthvi** [comment]
cc: @feloy

**Comment by feloy** [comment]
@feloy please double check

**Comment by valaparthvi** [comment]
I can confirm that the issue exists. I tested on 4.12, where it was just a warning, so the pod was allowed to be created, but the policies were not applied. On 4.13, the pods are not allowed to be created at all.

<details><summary>mongodb pod.yaml</summary>
<p>

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.131.0.45/23"],"mac_address":"0a:58:0a:83:00:2d","gateway_ips":["10.131.0.1"],"ip_addres
s":"10.131.0.45/23","gateway_ip":"10.131.0.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.131.0.45"
          ],
          "mac": "0a:58:0a:83:00:2d",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.131.0.45"
          ],
          "mac": "0a:58:0a:83:00:2d",
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2023-05-04T13:47:02Z"
  generateName: mongodb-dd4b4855-
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.10.2
    pod-template-hash: dd4b4855
  name: mongodb-dd4b4855-24dsd
  namespace: default
```

</p>
</details>
