### ISSUE TITLE
Odo dev on Mac not deploying podman pod for single container Django application

### ISSUE THREAD

**Issue by ucfchandra** [redhat-developer/odo#7236]
/kind bug

## What versions of software are you using?

**Operating System:**

Mac (not M1)

**Output of `odo version`:**
```
===============================================
⚠  unable to fetch the cluster server version
===============================================
odo v3.15.0 (10b5e8a8f-Homebrew)

Podman Client: 4.9.3
```

## How did you run odo exactly?
`ODO_PUSH_IMAGES=false odo dev --platform=podman`

## Actual behavior
```
✗  Deploying pod [4s]
Error occurred on Push - exit status 125: 
Complete Podman output:
Error: playing YAML file: initializing source [image]: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused
```

## Expected behavior

Running Django container

## Any logs, error output, etc?

Podman machine is initialized, started, and running, so that is not the issue. Might be an issue with my devfile. Attached below.

```
schemaVersion: 2.2.0

components:
  - name: announcements-image
    image:
      dockerfile:
        uri: ./Containerfile
        buildContext: .
      imageName: announcements-image
 
  - name: announcements
    container:
      image: announcements-image
      endpoints:
      - name: http-8000
        targetPort: 8000
      
```

Thank you :)
