### ISSUE TITLE
[RFE] Pass env vars to the `odo create` command

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/odo#837]
We can't specify ENV VAR to a component created using the command `odo create openjdk18 my-spring-boot --binary ./target/demo-0.0.1-SNAPSHOT.jar`

For some scenario, it is needed to pass runtime's ENV VAR to by example for Spring Boot, configure the application's property file to be used, enable the remote debugging, ...

```
envs:
  - name: SPRING_PROFILES_ACTIVE
    value: openshift-catalog
```

The existing `odo create` command should be extended to support to pass such parameters

```
odo create openjdk18 my-spring-boot --binary ./target/demo-0.0.1-SNAPSHOT.jar --envs SPRING_PROFILES_ACTIVE/openshift-catalog,...
```

or we could imagine to extend the command `odo link` to pass such info  or an Component Custom Resource containing such metadata could be used for that purpose

```
apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  creationTimestamp: null
  name: my-spring-boot
spec:
  deployment: innerloop
  envs:
  - name: SPRING_PROFILES_ACTIVE
    value: openshift-catalog
  exposeService: true
  runtime: springboot
  version: 1.5.16
```
